function result = run_netraai_parallel_capture_v5()
% RUN_NETRAAI_PARALLEL_CAPTURE_V5
%
% ANEYE / NetraAI Digital Twin V5
% Two-parallel-capture district configuration.
%
% BASE MODEL:
%   NetraAI_DigitalTwin_V4_District
%
% PURPOSE
% -------
% V4 demonstrated that one 120-second capture resource could not
% sustain the 100,000 screenings/year engineering requirement.
%
% V5 adds a second identical capture resource:
%
%                  -> Capture Queue 1 -> Camera 1 -
%                 /                            \
% Population -> Load Balancer                   -> Capture Merger
%                 \                            /
%                  -> Capture Queue 2 -> Camera 2 -
%                                                   |
%                                                   v
%                                                AI Queue
%
% PROVENANCE
% ------------------------------------------------------------
% REQUIREMENT:
%   100,000 screenings/year
%
% ASSUMPTION:
%   300 working days/year
%   8 hours/day
%   120 s fundus capture per station
%   30 s ophthalmology review
%   45 s human review
%
% MEASURED:
%   AI processing = 8.67151 s
%   ONE frozen reference case only
%
% ENGINEERING TEST:
%   balanced TRACE route mix 20% each
%
% SIMULATED:
%   waits
%   utilization
%   route throughput
%   unfinished cases at hard stop
%
% IMPORTANT:
%   This is an engineering digital twin, NOT clinical validation.

clc

fprintf('\n');
fprintf('========================================================\n');
fprintf(' ANEYE / NETRAAI DIGITAL TWIN V5\n');
fprintf(' TWO PARALLEL CAPTURE STATIONS\n');
fprintf('========================================================\n');

% ============================================================
% 1. PROJECT PATHS
% ============================================================

projectRoot = pwd;

srcDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'matlab', ...
    'src');

modelDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'simulink');

resultsDir = fullfile( ...
    modelDir, ...
    'results');

addpath(srcDir);

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

baseModel = ...
    'NetraAI_DigitalTwin_V4_District';

mdl = ...
    'NetraAI_DigitalTwin_V5_ParallelCapture';

baseModelFile = fullfile( ...
    modelDir, ...
    [baseModel '.mdl']);

modelFile = fullfile( ...
    modelDir, ...
    [mdl '.mdl']);

if exist(baseModelFile,'file') ~= 2

    error( ...
        ['V4 baseline model not found: ' ...
         baseModelFile]);

end

fprintf('\nV4 baseline:\n%s\n',baseModelFile);

% ============================================================
% 2. SCENARIO CONTRACT
% ============================================================

annualTarget = 100000;

workingDaysPerYear = 300;
operatingHoursPerDay = 8;

operatingSecondsPerYear = ...
    workingDaysPerYear ...
    * operatingHoursPerDay ...
    * 3600;

arrivalPeriod = ...
    operatingSecondsPerYear ...
    / annualTarget;

targetCasesPerDay = ...
    annualTarget ...
    / workingDaysPerYear;

targetCasesPerHour = ...
    annualTarget ...
    / (workingDaysPerYear * operatingHoursPerDay);

simulationHours = 8;

simulationTime = ...
    simulationHours * 3600;

captureTime = 120.0;
% ASSUMPTION

aiTime = 8.67151;
% MEASURED - SINGLE REFERENCE CASE

ophthalmologyTime = 30.0;
% ASSUMPTION

humanReviewTime = 45.0;
% ASSUMPTION

numCaptureStations = 2;

nominalCaptureCapacityPerHour = ...
    numCaptureStations ...
    * 3600 ...
    / captureTime;

nominalCaptureAnnualCapacity = ...
    nominalCaptureCapacityPerHour ...
    * operatingHoursPerDay ...
    * workingDaysPerYear;

capacityMarginPerHour = ...
    nominalCaptureCapacityPerHour ...
    - targetCasesPerHour;

% ============================================================
% 3. DISPLAY CONTRACT
% ============================================================

fprintf('\n--- V5 SCENARIO CONTRACT ---\n');

fprintf( ...
    'Annual requirement          : %.0f/year\n', ...
    annualTarget);

fprintf( ...
    'Required throughput         : %.2f cases/hour\n', ...
    targetCasesPerHour);

fprintf( ...
    'Arrival interval            : %.3f s\n', ...
    arrivalPeriod);

fprintf( ...
    'Capture stations            : %d\n', ...
    numCaptureStations);

fprintf( ...
    'Capture time/station        : %.2f s [ASSUMPTION]\n', ...
    captureTime);

fprintf( ...
    'Combined nominal capture    : %.2f cases/hour\n', ...
    nominalCaptureCapacityPerHour);

fprintf( ...
    'Nominal capture margin      : %.2f cases/hour\n', ...
    capacityMarginPerHour);

fprintf( ...
    'Nominal capture ceiling     : %.0f/year\n', ...
    nominalCaptureAnnualCapacity);

fprintf( ...
    'AI time                     : %.5f s [MEASURED-1 CASE]\n', ...
    aiTime);

fprintf( ...
    'TRACE route mix             : 20%% each [ENGINEERING TEST]\n');

fprintf( ...
    'Simulation horizon          : %.0f h\n', ...
    simulationHours);

% ============================================================
% 4. CLEAN PREVIOUS V5
% ============================================================

try
    close_system(mdl,0);
catch
end

if exist(modelFile,'file') == 2
    delete(modelFile);
end

% ============================================================
% 5. CLONE V4
% ============================================================

fprintf('\nLoading V4 baseline...\n');

load_system(baseModelFile);

save_system( ...
    baseModel, ...
    modelFile);

try
    close_system(baseModel,0);
catch
end

load_system(modelFile);

fprintf('V5 model cloned from validated V4.\n');

% ============================================================
% 6. LOAD SIMEVENTS LIBRARY
% ============================================================

load_system('simeventslib');

queueLib = ...
    'simeventslib/Queues/FIFO Queue';

serverLib = ...
    'simeventslib/Servers/Single Server';

outputSwitchLib = ...
    'simeventslib/Routing/Output Switch';

inputSwitchLib = ...
    'simeventslib/Routing/Input Switch';

% ============================================================
% 7. EXISTING BLOCK PATHS
% ============================================================

populationMerger = ...
    [mdl '/Population Merger'];

captureQueue1 = ...
    [mdl '/Capture Queue'];

captureServer1 = ...
    [mdl '/Fundus Capture'];

aiQueue = ...
    [mdl '/AI Queue'];

aiServer = ...
    [mdl '/TRACE AI Processing'];

ophQueue = ...
    [mdl '/Ophthalmology Queue'];

ophServer = ...
    [mdl '/Ophthalmologist Review'];

humanQueue = ...
    [mdl '/Human Review Queue'];

humanServer = ...
    [mdl '/Human Reviewer'];

% ============================================================
% 8. VERIFY V4 BLOCKS
% ============================================================

requiredBlocks = { ...
    populationMerger, ...
    captureQueue1, ...
    captureServer1, ...
    aiQueue, ...
    aiServer};

for k = 1:length(requiredBlocks)

    try
        get_param(requiredBlocks{k},'Handle');
    catch

        error( ...
            ['Expected V4 block missing: ' ...
             requiredBlocks{k}]);

    end

end

% ============================================================
% 9. DISCONNECT OLD SINGLE-CAPTURE PIPELINE
% ============================================================
%
% OLD:
% Population Merger -> Capture Queue -> Capture Server -> AI Queue
%
% Keep Queue1 -> Server1.
%
% Remove:
% Population Merger -> Queue1
% Server1 -> AI Queue

fprintf('\nReconfiguring capture topology...\n');

disconnectEntityInput( ...
    captureQueue1, ...
    1);

disconnectEntityInput( ...
    aiQueue, ...
    1);

fprintf('Old single-capture external connections removed.\n');

% ============================================================
% 10. MOVE EXISTING CAPTURE STATION 1
% ============================================================

set_param( ...
    captureQueue1, ...
    'Position', ...
    [900 145 1000 195]);

set_param( ...
    captureServer1, ...
    'Position', ...
    [1050 145 1180 195]);

set_param( ...
    captureQueue1, ...
    'Capacity', ...
    '1000');

set_param( ...
    captureServer1, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    captureServer1, ...
    'ServiceTime', ...
    num2str(captureTime,15));

% ============================================================
% 11. ADD CAPTURE LOAD BALANCER
% ============================================================

loadBalancer = ...
    [mdl '/Capture Load Balancer'];

try
    delete_block(loadBalancer);
catch
end

add_block( ...
    outputSwitchLib, ...
    loadBalancer, ...
    'Position', ...
    [720 165 840 325]);

set_param( ...
    loadBalancer, ...
    'NumberOutputPorts', ...
    '2');

set_param( ...
    loadBalancer, ...
    'SwitchingCriterion', ...
    'Round robin');

% ============================================================
% 12. ADD CAPTURE STATION 2
% ============================================================

captureQueue2 = ...
    [mdl '/Capture Queue 2'];

captureServer2 = ...
    [mdl '/Fundus Capture 2'];

try
    delete_block(captureQueue2);
catch
end

try
    delete_block(captureServer2);
catch
end

add_block( ...
    queueLib, ...
    captureQueue2, ...
    'Position', ...
    [900 300 1000 350]);

set_param( ...
    captureQueue2, ...
    'Capacity', ...
    '1000');

add_block( ...
    serverLib, ...
    captureServer2, ...
    'Position', ...
    [1050 300 1180 350]);

set_param( ...
    captureServer2, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    captureServer2, ...
    'ServiceTime', ...
    num2str(captureTime,15));

% ============================================================
% 13. ADD CAPTURE MERGER
% ============================================================

captureMerger = ...
    [mdl '/Capture Merger'];

try
    delete_block(captureMerger);
catch
end

add_block( ...
    inputSwitchLib, ...
    captureMerger, ...
    'Position', ...
    [1230 180 1350 315]);

set_param( ...
    captureMerger, ...
    'NumberInputPorts', ...
    '2');

set_param( ...
    captureMerger, ...
    'SwitchingCriterion', ...
    'Round robin');

% ============================================================
% 14. MOVE AI BLOCKS RIGHT
% ============================================================

set_param( ...
    aiQueue, ...
    'Position', ...
    [1400 220 1500 270]);

set_param( ...
    aiServer, ...
    'Position', ...
    [1550 220 1690 270]);

% ============================================================
% 15. CONNECT PARALLEL CAPTURE TOPOLOGY
% ============================================================

safeConnectEntity( ...
    mdl, ...
    populationMerger, ...
    loadBalancer);

safeConnectEntityOutput( ...
    mdl, ...
    loadBalancer, ...
    captureQueue1, ...
    1);

safeConnectEntityOutput( ...
    mdl, ...
    loadBalancer, ...
    captureQueue2, ...
    2);

% Queue1 -> Server1 already exists from V4.
% Recreate explicitly only if needed.

ensureEntityConnection( ...
    mdl, ...
    captureQueue1, ...
    captureServer1);

safeConnectEntity( ...
    mdl, ...
    captureQueue2, ...
    captureServer2);

safeConnectEntityToInput( ...
    mdl, ...
    captureServer1, ...
    captureMerger, ...
    1);

safeConnectEntityToInput( ...
    mdl, ...
    captureServer2, ...
    captureMerger, ...
    2);

safeConnectEntity( ...
    mdl, ...
    captureMerger, ...
    aiQueue);

fprintf('Parallel capture entity network connected.\n');

% ============================================================
% 16. VERIFY LOAD BALANCER
% ============================================================

if ~strcmp( ...
        get_param(loadBalancer,'SwitchingCriterion'), ...
        'Round robin')

    error('Capture Load Balancer is not Round robin.');

end

if ~strcmp( ...
        get_param(loadBalancer,'NumberOutputPorts'), ...
        '2')

    error('Capture Load Balancer does not have 2 outputs.');

end

fprintf('Capture load balancer configuration: PASS\n');

% ============================================================
% 17. ENABLE STATION 2 WAIT STATISTIC
% ============================================================

set_param( ...
    captureQueue2, ...
    'StatAverageWait', ...
    'on');

set_param( ...
    captureQueue2, ...
    'StatNumberDeparted', ...
    'off');

set_param( ...
    captureQueue2, ...
    'StatNumberInBlock', ...
    'off');

set_param( ...
    captureQueue2, ...
    'StatAverageQueueLength', ...
    'off');

set_param( ...
    captureQueue2, ...
    'StatNumberTimedout', ...
    'off');

% ============================================================
% 18. ENABLE STATION 2 UTILIZATION
% ============================================================

set_param( ...
    captureServer2, ...
    'StatUtilization', ...
    'on');

set_param( ...
    captureServer2, ...
    'StatNumberDeparted', ...
    'off');

set_param( ...
    captureServer2, ...
    'StatNumberInBlock', ...
    'off');

set_param( ...
    captureServer2, ...
    'StatNumberPreempted', ...
    'off');

set_param( ...
    captureServer2, ...
    'StatPendingEntity', ...
    'off');

set_param( ...
    captureServer2, ...
    'StatAverageWait', ...
    'off');

set_param( ...
    captureServer2, ...
    'StatNumberTimedout', ...
    'off');

% ============================================================
% 19. RENAME INHERITED WORKSPACE LOGGERS
% ============================================================

setLoggerVariable( ...
    mdl, ...
    'Route 1 Count', ...
    'v5Route1');

setLoggerVariable( ...
    mdl, ...
    'Route 2 Count', ...
    'v5Route2');

setLoggerVariable( ...
    mdl, ...
    'Route 3 Count', ...
    'v5Route3');

setLoggerVariable( ...
    mdl, ...
    'Route 4 Count', ...
    'v5Route4');

setLoggerVariable( ...
    mdl, ...
    'Route 5 Count', ...
    'v5Route5');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 1', ...
    'v5Capture1Wait');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 2', ...
    'v5AIWait');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 3', ...
    'v5OphWait');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 4', ...
    'v5HumanWait');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 1', ...
    'v5Capture1Util');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 2', ...
    'v5AIUtil');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 3', ...
    'v5OphUtil');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 4', ...
    'v5HumanUtil');

% ============================================================
% 20. UPDATE MODEL TO CREATE NEW STATISTICS PORTS
% ============================================================

set_param( ...
    mdl, ...
    'SimulationCommand', ...
    'update');

% ============================================================
% 21. ADD CAPTURE STATION 2 WAIT LOGGER
% ============================================================

capture2WaitLogger = ...
    [mdl '/Metric Capture2 Wait'];

try
    delete_block(capture2WaitLogger);
catch
end

add_block( ...
    'simulink/Sinks/To Workspace', ...
    capture2WaitLogger, ...
    'VariableName', ...
    'v5Capture2Wait', ...
    'SaveFormat', ...
    'Array', ...
    'Position', ...
    [1210 380 1340 415]);

queue2Ports = get_param( ...
    captureQueue2, ...
    'PortHandles');

waitLoggerPorts = get_param( ...
    capture2WaitLogger, ...
    'PortHandles');

if isempty(queue2Ports.Outport)

    error( ...
        'Capture Queue 2 statistics port was not created.');

end

add_line( ...
    mdl, ...
    queue2Ports.Outport(1), ...
    waitLoggerPorts.Inport(1), ...
    'autorouting', ...
    'on');

% ============================================================
% 22. ADD CAPTURE STATION 2 UTIL LOGGER
% ============================================================

capture2UtilLogger = ...
    [mdl '/Metric Capture2 Util'];

try
    delete_block(capture2UtilLogger);
catch
end

add_block( ...
    'simulink/Sinks/To Workspace', ...
    capture2UtilLogger, ...
    'VariableName', ...
    'v5Capture2Util', ...
    'SaveFormat', ...
    'Array', ...
    'Position', ...
    [1210 430 1340 465]);

server2Ports = get_param( ...
    captureServer2, ...
    'PortHandles');

utilLoggerPorts = get_param( ...
    capture2UtilLogger, ...
    'PortHandles');

if isempty(server2Ports.Outport)

    error( ...
        'Fundus Capture 2 utilization port was not created.');

end

add_line( ...
    mdl, ...
    server2Ports.Outport(1), ...
    utilLoggerPorts.Inport(1), ...
    'autorouting', ...
    'on');

% ============================================================
% 23. REASSERT DISTRICT SERVICE VALUES
% ============================================================

set_param( ...
    aiServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    aiServer, ...
    'ServiceTime', ...
    num2str(aiTime,15));

set_param( ...
    ophServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    ophServer, ...
    'ServiceTime', ...
    num2str(ophthalmologyTime,15));

set_param( ...
    humanServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    humanServer, ...
    'ServiceTime', ...
    num2str(humanReviewTime,15));

% ============================================================
% 24. SIMULATION SETTINGS
% ============================================================

set_param( ...
    mdl, ...
    'StopTime', ...
    num2str(simulationTime));

set_param( ...
    mdl, ...
    'Solver', ...
    'VariableStepDiscrete');

set_param( ...
    mdl, ...
    'MaxStep', ...
    '1');

% ============================================================
% 25. DESCRIPTION
% ============================================================

descriptionText = [ ...
    'ANEYE / NetraAI Digital Twin V5. ' ...
    'District 100000 screenings/year engineering scenario ' ...
    'with two parallel fundus capture resources. ' ...
    'Capture service time is an explicit assumption. ' ...
    'AI runtime is measured from one frozen reference case. ' ...
    'Balanced route mix is an engineering test and not ' ...
    'clinical prevalence.'];

try

    set_param( ...
        mdl, ...
        'Description', ...
        descriptionText);

catch
end

save_system( ...
    mdl, ...
    modelFile);

fprintf('\nParallel capture model construction: PASS\n');

% ============================================================
% 26. CLEAR BASE WORKSPACE OUTPUTS
% ============================================================

evalin( ...
    'base', ...
    ['clear ' ...
     'v5Route1 v5Route2 v5Route3 v5Route4 v5Route5 ' ...
     'v5Capture1Wait v5Capture2Wait ' ...
     'v5AIWait v5OphWait v5HumanWait ' ...
     'v5Capture1Util v5Capture2Util ' ...
     'v5AIUtil v5OphUtil v5HumanUtil']);

% ============================================================
% 27. RUN SIMULATION IN BASE WORKSPACE
% ============================================================

fprintf('\nRunning V5 two-capture simulation...\n');

simCommand = [ ...
    'sim(''' ...
    mdl ...
    ''');'];

evalin( ...
    'base', ...
    simCommand);

fprintf('Simulation complete.\n');

% ============================================================
% 28. VERIFY OUTPUT VARIABLES
% ============================================================

requiredVars = { ...
    'v5Route1', ...
    'v5Route2', ...
    'v5Route3', ...
    'v5Route4', ...
    'v5Route5', ...
    'v5Capture1Wait', ...
    'v5Capture2Wait', ...
    'v5AIWait', ...
    'v5OphWait', ...
    'v5HumanWait', ...
    'v5Capture1Util', ...
    'v5Capture2Util', ...
    'v5AIUtil', ...
    'v5OphUtil', ...
    'v5HumanUtil'};

fprintf('\nChecking V5 logged outputs...\n');

for k = 1:length(requiredVars)

    existsFlag = evalin( ...
        'base', ...
        ['exist(''' ...
         requiredVars{k} ...
         ''',''var'')']);

    if existsFlag ~= 1

        error( ...
            ['Missing V5 output variable: ' ...
             requiredVars{k}]);

    end

end

fprintf('All V5 outputs: PASS\n');

% ============================================================
% 29. ROUTE COUNTS
% ============================================================

counts = zeros(1,5);

for k = 1:5

    x = evalin( ...
        'base', ...
        ['v5Route' num2str(k)]);

    counts(k) = ...
        getLastMetric(x);

end

% ============================================================
% 30. QUEUE WAITS
% ============================================================

capture1Wait = ...
    getLastMetric( ...
        evalin('base','v5Capture1Wait'));

capture2Wait = ...
    getLastMetric( ...
        evalin('base','v5Capture2Wait'));

aiWait = ...
    getLastMetric( ...
        evalin('base','v5AIWait'));

ophWait = ...
    getLastMetric( ...
        evalin('base','v5OphWait'));

humanWait = ...
    getLastMetric( ...
        evalin('base','v5HumanWait'));

% ============================================================
% 31. UTILIZATION
% ============================================================

capture1Util = ...
    getLastMetric( ...
        evalin('base','v5Capture1Util'));

capture2Util = ...
    getLastMetric( ...
        evalin('base','v5Capture2Util'));

aiUtil = ...
    getLastMetric( ...
        evalin('base','v5AIUtil'));

ophUtil = ...
    getLastMetric( ...
        evalin('base','v5OphUtil'));

humanUtil = ...
    getLastMetric( ...
        evalin('base','v5HumanUtil'));

% ============================================================
% 32. DERIVED THROUGHPUT
% ============================================================

totalCompleted = ...
    sum(counts);

expectedGenerated = ...
    floor( ...
        simulationTime ...
        / arrivalPeriod) ...
    + 1;

unfinishedAtStop = ...
    max( ...
        0, ...
        expectedGenerated ...
        - totalCompleted);

observedCasesPerHour = ...
    totalCompleted ...
    / simulationHours;

observedAnnualEquivalent = ...
    observedCasesPerHour ...
    * operatingHoursPerDay ...
    * workingDaysPerYear;

completionFraction = ...
    totalCompleted ...
    / expectedGenerated;

maxCaptureWait = ...
    max( ...
        [capture1Wait capture2Wait]);

maxCaptureUtil = ...
    max( ...
        [capture1Util capture2Util]);

allResourceUtil = [ ...
    capture1Util, ...
    capture2Util, ...
    aiUtil, ...
    ophUtil, ...
    humanUtil];

resourceNames = { ...
    'CAPTURE_STATION_1', ...
    'CAPTURE_STATION_2', ...
    'TRACE_AI', ...
    'OPHTHALMOLOGIST', ...
    'HUMAN_REVIEWER'};

[maxUtil,maxIndex] = ...
    max(allResourceUtil);

highestUtilizationResource = ...
    resourceNames{maxIndex};

% ============================================================
% 33. SUSTAINABILITY DECISION
% ============================================================
%
% Do NOT use hard-stop completed count alone because cases
% arriving immediately before t = 8 h can still legitimately be
% in service when the simulation stops.
%
% We ask instead:
%
% 1. Does nominal capture capacity exceed incoming demand?
% 2. Is either capture resource saturated?
% 3. Is capture queue waiting accumulating?
% 4. Are downstream resources saturated?

nominalCapacityAdequate = ...
    nominalCaptureCapacityPerHour ...
    > targetCasesPerHour;

captureStable = ...
    maxCaptureUtil < 0.95 ...
    && maxCaptureWait < 1.0;

downstreamStable = ...
    aiUtil < 0.95 ...
    && ophUtil < 0.95 ...
    && humanUtil < 0.95;

targetSustained = ...
    nominalCapacityAdequate ...
    && captureStable ...
    && downstreamStable;

% ============================================================
% 34. RESULT STRUCT
% ============================================================

result.scenario = ...
    'DISTRICT_100K_TWO_CAPTURE_V1';

result.provenance.annualTarget = ...
    'REQUIREMENT';

result.provenance.captureTime = ...
    'ASSUMPTION';

result.provenance.aiTime = ...
    'MEASURED_SINGLE_REFERENCE_CASE';

result.provenance.routeMix = ...
    'ENGINEERING_TEST';

result.provenance.outputMetrics = ...
    'SIMULATED';

result.target.annualCases = ...
    annualTarget;

result.target.casesPerHour = ...
    targetCasesPerHour;

result.target.arrivalPeriodSec = ...
    arrivalPeriod;

result.capture.stationCount = ...
    numCaptureStations;

result.capture.serviceTimeSec = ...
    captureTime;

result.capture.nominalCapacityPerHour = ...
    nominalCaptureCapacityPerHour;

result.capture.nominalAnnualCeiling = ...
    nominalCaptureAnnualCapacity;

result.capture.capacityMarginPerHour = ...
    capacityMarginPerHour;

result.routes = ...
    counts;

result.wait.capture1Sec = ...
    capture1Wait;

result.wait.capture2Sec = ...
    capture2Wait;

result.wait.aiSec = ...
    aiWait;

result.wait.ophthalmologySec = ...
    ophWait;

result.wait.humanReviewSec = ...
    humanWait;

result.utilization.capture1 = ...
    capture1Util;

result.utilization.capture2 = ...
    capture2Util;

result.utilization.ai = ...
    aiUtil;

result.utilization.ophthalmology = ...
    ophUtil;

result.utilization.humanReview = ...
    humanUtil;

result.throughput.generated = ...
    expectedGenerated;

result.throughput.completed = ...
    totalCompleted;

result.throughput.unfinishedAtStop = ...
    unfinishedAtStop;

result.throughput.completionFraction = ...
    completionFraction;

result.throughput.observedCasesPerHour = ...
    observedCasesPerHour;

result.throughput.observedAnnualEquivalent = ...
    observedAnnualEquivalent;

result.highestUtilizationResource = ...
    highestUtilizationResource;

result.highestUtilization = ...
    maxUtil;

result.nominalCapacityAdequate = ...
    nominalCapacityAdequate;

result.captureStable = ...
    captureStable;

result.downstreamStable = ...
    downstreamStable;

result.targetSustained = ...
    targetSustained;

% ============================================================
% 35. PRINT V5 RESULTS
% ============================================================

fprintf('\n');
fprintf('========================================================\n');
fprintf(' NETRAAI V5 PARALLEL CAPTURE RESULTS\n');
fprintf('========================================================\n');

fprintf('\n--- TRACE ROUTES [SIMULATED] ---\n');

fprintf('Routine             : %.0f\n',counts(1));
fprintf('Ophthalmology       : %.0f\n',counts(2));
fprintf('Human Review        : %.0f\n',counts(3));
fprintf('Review / Recapture  : %.0f\n',counts(4));
fprintf('Recapture           : %.0f\n',counts(5));

fprintf('\n--- CAPTURE QUEUES [SIMULATED] ---\n');

fprintf( ...
    'Station 1 wait      : %.3f s\n', ...
    capture1Wait);

fprintf( ...
    'Station 2 wait      : %.3f s\n', ...
    capture2Wait);

fprintf('\n--- DOWNSTREAM QUEUES [SIMULATED] ---\n');

fprintf('AI wait             : %.3f s\n',aiWait);
fprintf('Ophthalmology wait  : %.3f s\n',ophWait);
fprintf('Human Review wait   : %.3f s\n',humanWait);

fprintf('\n--- RESOURCE UTILIZATION [SIMULATED] ---\n');

fprintf( ...
    'Capture Station 1   : %.4f\n', ...
    capture1Util);

fprintf( ...
    'Capture Station 2   : %.4f\n', ...
    capture2Util);

fprintf( ...
    'TRACE AI            : %.4f\n', ...
    aiUtil);

fprintf( ...
    'Ophthalmologist     : %.4f\n', ...
    ophUtil);

fprintf( ...
    'Human Reviewer      : %.4f\n', ...
    humanUtil);

fprintf('\n--- CAPACITY ---\n');

fprintf( ...
    'Required rate       : %.2f cases/hour\n', ...
    targetCasesPerHour);

fprintf( ...
    '2-camera ceiling    : %.2f cases/hour\n', ...
    nominalCaptureCapacityPerHour);

fprintf( ...
    'Capacity margin     : %.2f cases/hour\n', ...
    capacityMarginPerHour);

fprintf( ...
    'Generated           : %.0f\n', ...
    expectedGenerated);

fprintf( ...
    'Completed           : %.0f\n', ...
    totalCompleted);

fprintf( ...
    'Unfinished @ stop   : %.0f\n', ...
    unfinishedAtStop);

fprintf( ...
    'Completion fraction : %.4f\n', ...
    completionFraction);

fprintf( ...
    'Observed rate       : %.2f cases/hour\n', ...
    observedCasesPerHour);

fprintf( ...
    'Observed annual eq. : %.0f/year\n', ...
    observedAnnualEquivalent);

fprintf('\n--- SYSTEM CHECK ---\n');

fprintf( ...
    'Highest utilization : %s\n', ...
    highestUtilizationResource);

fprintf( ...
    'Utilization         : %.4f\n', ...
    maxUtil);

fprintf( ...
    'Nominal capacity    : %d\n', ...
    nominalCapacityAdequate);

fprintf( ...
    'Capture stable      : %d\n', ...
    captureStable);

fprintf( ...
    'Downstream stable   : %d\n', ...
    downstreamStable);

fprintf('\n');

if targetSustained

    fprintf( ...
        'TARGET STATUS: SUSTAINED IN THIS ENGINEERING SCENARIO\n');

else

    fprintf( ...
        'TARGET STATUS: CAPACITY GAP REMAINS\n');

end

fprintf('========================================================\n');

% ============================================================
% 36. V4 COMPARISON
% ============================================================

v4ResultFile = fullfile( ...
    resultsDir, ...
    'NetraAI_V4_District_100K_Result.mat');

if exist(v4ResultFile,'file') == 2

    v4Data = load(v4ResultFile);

    if isfield(v4Data,'result')

        v4 = v4Data.result;

        fprintf('\n');
        fprintf('========================================================\n');
        fprintf(' V4 vs V5 RESOURCE INTERVENTION\n');
        fprintf('========================================================\n');

        fprintf( ...
            'V4 capture stations       : 1\n');

        fprintf( ...
            'V5 capture stations       : 2\n');

        fprintf( ...
            'V4 capture wait           : %.1f s\n', ...
            v4.wait.captureSec);

        fprintf( ...
            'V5 maximum capture wait   : %.1f s\n', ...
            maxCaptureWait);

        fprintf( ...
            'V4 capture utilization    : %.4f\n', ...
            v4.utilization.capture);

        fprintf( ...
            'V5 max capture utilization: %.4f\n', ...
            maxCaptureUtil);

        fprintf( ...
            'V4 annualized completion  : %.0f/year\n', ...
            v4.throughput.annualizedCapacity);

        fprintf( ...
            'V5 nominal capture ceiling: %.0f/year\n', ...
            nominalCaptureAnnualCapacity);

        fprintf( ...
            'V4 target status          : CAPACITY GAP\n');

        if targetSustained

            fprintf( ...
                'V5 target status          : SUSTAINED\n');

        else

            fprintf( ...
                'V5 target status          : GAP REMAINS\n');

        end

        fprintf('========================================================\n');

    end

end

% ============================================================
% 37. SAVE RESULT
% ============================================================

resultMat = fullfile( ...
    resultsDir, ...
    'NetraAI_V5_ParallelCapture_Result.mat');

save( ...
    resultMat, ...
    'result');

% ============================================================
% 38. SAVE TEXT REPORT
% ============================================================

reportFile = fullfile( ...
    resultsDir, ...
    'NetraAI_V5_ParallelCapture_Report.txt');

fid = fopen(reportFile,'w');

if fid ~= -1

    fprintf(fid, ...
        'ANEYE / NetraAI Digital Twin V5\n');

    fprintf(fid, ...
        'Two Parallel Capture Stations\n\n');

    fprintf(fid, ...
        'Annual requirement: %.0f\n', ...
        annualTarget);

    fprintf(fid, ...
        'Required cases/hour: %.4f\n', ...
        targetCasesPerHour);

    fprintf(fid, ...
        'Capture stations: %d\n', ...
        numCaptureStations);

    fprintf(fid, ...
        'Capture service: %.4f s [ASSUMPTION]\n', ...
        captureTime);

    fprintf(fid, ...
        'AI service: %.5f s [MEASURED_SINGLE_REFERENCE_CASE]\n', ...
        aiTime);

    fprintf(fid, ...
        'Combined nominal capture capacity: %.4f/hour\n', ...
        nominalCaptureCapacityPerHour);

    fprintf(fid, ...
        '\nSIMULATED CAPTURE WAIT\n');

    fprintf(fid, ...
        'Station 1: %.6f s\n', ...
        capture1Wait);

    fprintf(fid, ...
        'Station 2: %.6f s\n', ...
        capture2Wait);

    fprintf(fid, ...
        '\nSIMULATED UTILIZATION\n');

    fprintf(fid, ...
        'Capture 1: %.6f\n', ...
        capture1Util);

    fprintf(fid, ...
        'Capture 2: %.6f\n', ...
        capture2Util);

    fprintf(fid, ...
        'TRACE AI: %.6f\n', ...
        aiUtil);

    fprintf(fid, ...
        'Ophthalmologist: %.6f\n', ...
        ophUtil);

    fprintf(fid, ...
        'Human Reviewer: %.6f\n', ...
        humanUtil);

    fprintf(fid, ...
        '\nTHROUGHPUT\n');

    fprintf(fid, ...
        'Generated: %.0f\n', ...
        expectedGenerated);

    fprintf(fid, ...
        'Completed: %.0f\n', ...
        totalCompleted);

    fprintf(fid, ...
        'Unfinished at hard stop: %.0f\n', ...
        unfinishedAtStop);

    fprintf(fid, ...
        'Observed cases/hour: %.4f\n', ...
        observedCasesPerHour);

    fprintf(fid, ...
        'Observed annual equivalent: %.0f\n', ...
        observedAnnualEquivalent);

    fprintf(fid, ...
        'Nominal capture annual ceiling: %.0f\n', ...
        nominalCaptureAnnualCapacity);

    fprintf(fid, ...
        '\nSYSTEM\n');

    fprintf(fid, ...
        'Highest utilization resource: %s\n', ...
        highestUtilizationResource);

    fprintf(fid, ...
        'Highest utilization: %.6f\n', ...
        maxUtil);

    fprintf(fid, ...
        'Nominal capacity adequate: %d\n', ...
        nominalCapacityAdequate);

    fprintf(fid, ...
        'Capture stable: %d\n', ...
        captureStable);

    fprintf(fid, ...
        'Downstream stable: %d\n', ...
        downstreamStable);

    fprintf(fid, ...
        'Target sustained: %d\n', ...
        targetSustained);

    fclose(fid);

end

% ============================================================
% 39. FINAL SAVE / OPEN
% ============================================================

save_system( ...
    mdl, ...
    modelFile);

fprintf('\nSaved V5 result:\n%s\n',resultMat);

fprintf('\nSaved V5 report:\n%s\n',reportFile);

fprintf('\nV5 model:\n%s\n',modelFile);

open_system(mdl);

end


% ============================================================
% HELPER - SET TO WORKSPACE VARIABLE NAME
% ============================================================

function setLoggerVariable( ...
    mdl, ...
    blockName, ...
    variableName)

blockPath = ...
    [mdl '/' blockName];

try

    set_param( ...
        blockPath, ...
        'VariableName', ...
        variableName);

catch ME

    error( ...
        ['Unable to configure logger ' ...
         blockName ...
         ': ' ...
         ME.message]);

end

end


% ============================================================
% HELPER - SAFE STANDARD ENTITY CONNECTION
% ============================================================

function safeConnectEntity( ...
    model, ...
    source, ...
    destination)

src = get_param( ...
    source, ...
    'PortHandles');

dst = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput(src,1);
dstPort = getEntityInput(dst,1);

disconnectPortLine(srcPort);
disconnectPortLine(dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% HELPER - SPECIFIC OUTPUT CONNECTION
% ============================================================

function safeConnectEntityOutput( ...
    model, ...
    source, ...
    destination, ...
    outputIndex)

src = get_param( ...
    source, ...
    'PortHandles');

dst = get_param( ...
    destination, ...
    'PortHandles');

srcPort = ...
    getEntityOutput( ...
        src, ...
        outputIndex);

dstPort = ...
    getEntityInput( ...
        dst, ...
        1);

disconnectPortLine(srcPort);
disconnectPortLine(dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% HELPER - SPECIFIC INPUT CONNECTION
% ============================================================

function safeConnectEntityToInput( ...
    model, ...
    source, ...
    destination, ...
    inputIndex)

src = get_param( ...
    source, ...
    'PortHandles');

dst = get_param( ...
    destination, ...
    'PortHandles');

srcPort = ...
    getEntityOutput( ...
        src, ...
        1);

dstPort = ...
    getEntityInput( ...
        dst, ...
        inputIndex);

disconnectPortLine(srcPort);
disconnectPortLine(dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% HELPER - ENSURE EXISTING CONNECTION
% ============================================================

function ensureEntityConnection( ...
    model, ...
    source, ...
    destination)

src = get_param( ...
    source, ...
    'PortHandles');

srcPort = ...
    getEntityOutput( ...
        src, ...
        1);

lineHandle = -1;

try
    lineHandle = get_param(srcPort,'Line');
catch
end

if isempty(lineHandle) || lineHandle == -1

    safeConnectEntity( ...
        model, ...
        source, ...
        destination);

end

end


% ============================================================
% HELPER - DISCONNECT ENTITY INPUT
% ============================================================

function disconnectEntityInput( ...
    blockPath, ...
    inputIndex)

ph = get_param( ...
    blockPath, ...
    'PortHandles');

port = getEntityInput( ...
    ph, ...
    inputIndex);

disconnectPortLine(port);

end


% ============================================================
% HELPER - REMOVE CONNECTED LINE
% ============================================================

function disconnectPortLine(portHandle)

if isempty(portHandle)
    return;
end

try

    lineHandle = ...
        get_param( ...
            portHandle, ...
            'Line');

    if ~isempty(lineHandle) && ...
            lineHandle ~= -1

        delete_line(lineHandle);

    end

catch
end

end


% ============================================================
% HELPER - ENTITY OUTPUT HANDLE
% ============================================================

function h = getEntityOutput( ...
    portHandles, ...
    index)

if isfield(portHandles,'RConn') && ...
        length(portHandles.RConn) >= index

    h = portHandles.RConn(index);
    return;

end

if isfield(portHandles,'Outport') && ...
        length(portHandles.Outport) >= index

    h = portHandles.Outport(index);
    return;

end

error( ...
    ['Unable to resolve entity output port ' ...
     num2str(index)]);

end


% ============================================================
% HELPER - ENTITY INPUT HANDLE
% ============================================================

function h = getEntityInput( ...
    portHandles, ...
    index)

if isfield(portHandles,'LConn') && ...
        length(portHandles.LConn) >= index

    h = portHandles.LConn(index);
    return;

end

if isfield(portHandles,'Inport') && ...
        length(portHandles.Inport) >= index

    h = portHandles.Inport(index);
    return;

end

error( ...
    ['Unable to resolve entity input port ' ...
     num2str(index)]);

end


% ============================================================
% HELPER - LAST TO WORKSPACE METRIC
% ============================================================

function value = getLastMetric(data)

if isempty(data)

    value = 0;

elseif size(data,2) >= 2

    value = data(end,2);

else

    value = data(end);

end

end