function results = run_netraai_resource_sweep_v7()
% RUN_NETRAAI_RESOURCE_SWEEP_V7
%
% ANEYE / NetraAI Digital Twin V7
% CORRECTED DISTRICT RESOURCE-SIZING STRESS SWEEP
%
% MATLAB / SimEvents R2014a compatible.
%
% ============================================================
% VALIDATED BASELINE
% ============================================================
%
% NetraAI_DigitalTwin_V6_RecaptureLoop
%
% ============================================================
% PURPOSE
% ============================================================
%
% Evaluate district screening capacity across:
%
%   Capture stations:
%       1
%       2
%       3
%
%   Recapture workload:
%       0%
%       5%
%       10%
%       15%
%       20%
%       25%
%       30%
%
% Total:
%
%       3 x 7 = 21 scenarios
%
% ============================================================
% PROVENANCE
% ============================================================
%
% REQUIREMENT
%   100,000 primary screenings/year
%
% MEASURED
%   AI processing = 8.67151 s
%   single frozen reference case
%
% ASSUMPTION
%   300 operating days/year
%   8 operating hours/day
%   fundus capture = 120 s
%   ophthalmology review = 30 s
%   human review = 45 s
%   recapture preparation = 20 s
%
% ENGINEERING SENSITIVITY TEST
%   recapture workload = 0% to 30%
%
% ENGINEERING GUARDRAILS
%   capture utilization < 95%
%   max capture wait < primary interarrival interval
%   downstream utilization < 95%
%   >=98% primary completion within 8-hour horizon
%
% These are NOT clinical or regulatory thresholds.
%
% ============================================================
% IMPORTANT FIXES IN THIS VERSION
% ============================================================
%
% 1. TRACE Router is explicitly preserved.
%
% 2. TRACE downstream topology is rebuilt and validated before
%    every simulation.
%
% 3. Recapture uses the validated V6 Path Combiner feedback
%    architecture.
%
% 4. Representative R30 models are saved using COPYFILE rather
%    than save_system(...,newname), avoiding R2014a open-model
%    naming conflicts.
%
% 5. Invalid zero-terminal-output simulations cause an ERROR
%    rather than entering the resource-sizing matrix.
%
% ============================================================

clc

fprintf('\n');
fprintf('============================================================\n');
fprintf(' ANEYE / NETRAAI DIGITAL TWIN V7\n');
fprintf(' CORRECTED RESOURCE-SIZING STRESS SWEEP\n');
fprintf('============================================================\n');

% ============================================================
% 1. EXECUTION MODE
% ============================================================
%
% Smoke test already passed.
%
% FALSE = full 21-scenario sweep.
% TRUE  = only 2-camera / 20%% recapture validation.
% ============================================================

SMOKE_ONLY = false;

% ============================================================
% 2. PROJECT PATHS
% ============================================================

projectRoot = pwd;

srcDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'matlab', ...
    'src');

modelDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'simulink');

resultsDir = fullfile( ...
    modelDir, ...
    'results');

addpath(srcDir);

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

baseModel = ...
    'NetraAI_DigitalTwin_V6_RecaptureLoop';

baseModelFile = fullfile( ...
    modelDir, ...
    [baseModel '.mdl']);

workingModel = ...
    'NetraAI_DigitalTwin_V7_Working';

workingModelFile = fullfile( ...
    modelDir, ...
    [workingModel '.mdl']);

if exist(baseModelFile,'file') ~= 2

    error( ...
        ['Validated V6 baseline not found: ' ...
         baseModelFile]);

end

fprintf('\nValidated V6 baseline:\n%s\n', ...
    baseModelFile);

% ============================================================
% 3. DISTRICT CONTRACT
% ============================================================

annualTarget = 100000;

workingDays = 300;

hoursPerDay = 8;

simulationHours = 8;

simulationTime = ...
    simulationHours * 3600;

operatingSecondsYear = ...
    workingDays ...
    * hoursPerDay ...
    * 3600;

arrivalPeriod = ...
    operatingSecondsYear ...
    / annualTarget;

requiredPrimaryRate = ...
    annualTarget ...
    / (workingDays * hoursPerDay);

captureTime = 120.0;
% ASSUMPTION

aiTime = 8.67151;
% MEASURED - SINGLE FROZEN REFERENCE CASE

ophthalmologyTime = 30.0;
% ASSUMPTION

humanReviewTime = 45.0;
% ASSUMPTION

recapturePreparationTime = 20.0;
% ASSUMPTION

captureCapacityPerStation = ...
    3600 / captureTime;

% ============================================================
% 4. SWEEP DEFINITION
% ============================================================

if SMOKE_ONLY

    cameraCounts = ...
        [2];

    recapturePercentages = ...
        [20];

    fprintf('\n');
    fprintf('*** SMOKE TEST MODE ENABLED ***\n');

else

    cameraCounts = ...
        [1 2 3];

    recapturePercentages = ...
        [0 5 10 15 20 25 30];

    fprintf('\n');
    fprintf('*** FULL 21-SCENARIO SWEEP ENABLED ***\n');

end

numCameraScenarios = ...
    length(cameraCounts);

numRecaptureScenarios = ...
    length(recapturePercentages);

numScenarios = ...
    numCameraScenarios ...
    * numRecaptureScenarios;

% ============================================================
% 5. PRINT SCENARIO CONTRACT
% ============================================================

fprintf('\n--- V7 SCENARIO CONTRACT ---\n');

fprintf( ...
    'Annual requirement        : %.0f/year\n', ...
    annualTarget);

fprintf( ...
    'Required primary rate     : %.4f cases/hour\n', ...
    requiredPrimaryRate);

fprintf( ...
    'Primary arrival interval  : %.3f s\n', ...
    arrivalPeriod);

fprintf( ...
    'Capture service           : %.2f s [ASSUMPTION]\n', ...
    captureTime);

fprintf( ...
    'Per-camera capacity       : %.2f capture events/hour\n', ...
    captureCapacityPerStation);

fprintf( ...
    'AI service                : %.5f s [MEASURED-1 CASE]\n', ...
    aiTime);

fprintf( ...
    'Recapture preparation     : %.2f s [ASSUMPTION]\n', ...
    recapturePreparationTime);

fprintf( ...
    'Simulation horizon        : %.0f h/scenario\n', ...
    simulationHours);

fprintf( ...
    'Number of scenarios       : %d\n', ...
    numScenarios);

% ============================================================
% 6. RESULT MATRIX
% ============================================================
%
% Columns:
%
%  1 Cameras
%  2 RecapturePct
%  3 TheoreticalCaptureUtil
%  4 PrimaryGenerated
%  5 PrimaryCompleted
%  6 PrimaryIncomplete
%  7 CompletionFraction
%  8 RecaptureCompleted
%  9 ObservedRecapturePct
% 10 Capture1Util
% 11 Capture2Util
% 12 Capture3Util
% 13 MaxCaptureUtil
% 14 Capture1WaitSec
% 15 Capture2WaitSec
% 16 Capture3WaitSec
% 17 MaxCaptureWaitSec
% 18 AIUtil
% 19 OphUtil
% 20 HumanUtil
% 21 PrimaryRatePerHour
% 22 AnnualizedPrimaryEq
% 23 Stable
% ============================================================

M = zeros(numScenarios,23);

scenarioIndex = 0;

% ============================================================
% 7. LOAD SIMEVENTS LIBRARY
% ============================================================

load_system('simeventslib');

% ============================================================
% 8. BEGIN FULL SWEEP
% ============================================================

for cameraIndex = 1:numCameraScenarios

    cameraCount = ...
        cameraCounts(cameraIndex);

    for recaptureIndex = 1:numRecaptureScenarios

        recapturePercent = ...
            recapturePercentages(recaptureIndex);

        recaptureFraction = ...
            recapturePercent / 100;

        scenarioIndex = ...
            scenarioIndex + 1;

        fprintf('\n');
        fprintf('------------------------------------------------------------\n');

        fprintf( ...
            ' V7 SCENARIO %02d/%02d : %d CAMERA(S), %d%% RECAPTURE\n', ...
            scenarioIndex, ...
            numScenarios, ...
            cameraCount, ...
            recapturePercent);

        fprintf('------------------------------------------------------------\n');

        % ====================================================
        % 8A. CLOSE POSSIBLE LEFTOVER WORKING MODEL
        % ====================================================

        try
            close_system(workingModel,0);
        catch
        end

        % ====================================================
        % 8B. DELETE OLD WORKING FILE
        % ====================================================

        if exist(workingModelFile,'file') == 2

            try
                delete(workingModelFile);
            catch
            end

        end

        % ====================================================
        % 8C. CLONE VALIDATED V6
        % ====================================================

        load_system(baseModelFile);

        save_system( ...
            baseModel, ...
            workingModelFile);

        try
            close_system(baseModel,0);
        catch
        end

        load_system(workingModelFile);

        mdl = workingModel;

        fprintf('Fresh V7 model cloned from validated V6.\n');

        % ====================================================
        % 8D. VERIFY TRACE ROUTER BEFORE MODIFICATION
        % ====================================================

        traceRouter = ...
            [mdl '/TRACE Router'];

        verifyBlockExists( ...
            traceRouter, ...
            'TRACE Router missing before V7 construction.');

        fprintf('TRACE Router before population rebuild: PASS\n');

        % ====================================================
        % 8E. CREATE DETERMINISTIC ROUTE SEQUENCE
        % ====================================================

        recaptureSlots = ...
            round(recapturePercent / 5);

        routeSequence = ...
            buildRouteSequence20( ...
                recaptureSlots);

        fprintf('Primary route sequence: ');

        for q = 1:length(routeSequence)

            fprintf( ...
                '%d ', ...
                routeSequence(q));

        end

        fprintf('\n');

        % ====================================================
        % 8F. REBUILD PRIMARY POPULATION
        % ====================================================

        configureRoutePopulation( ...
            mdl, ...
            routeSequence);

        % ====================================================
        % 8G. REPAIR TRACE PIPELINE
        % ====================================================

        repairTracePipeline(mdl);

        verifyCriticalFlow(mdl);

        removeDanglingLines(mdl);

        % ====================================================
        % 8H. CONFIGURE NUMBER OF CAMERAS
        % ====================================================

        configureCaptureResources( ...
            mdl, ...
            cameraCount, ...
            captureTime);

        % ====================================================
        % 8I. REPAIR AGAIN AFTER CAMERA MODIFICATION
        % ====================================================

        repairTracePipeline(mdl);

        verifyCriticalFlow(mdl);

        removeDanglingLines(mdl);

        % ====================================================
        % 8J. REASSERT SERVICE TIMES
        % ====================================================

        set_param( ...
            [mdl '/TRACE AI Processing'], ...
            'ServiceTimeFrom', ...
            'Dialog');

        set_param( ...
            [mdl '/TRACE AI Processing'], ...
            'ServiceTime', ...
            num2str(aiTime,15));

        set_param( ...
            [mdl '/Ophthalmologist Review'], ...
            'ServiceTimeFrom', ...
            'Dialog');

        set_param( ...
            [mdl '/Ophthalmologist Review'], ...
            'ServiceTime', ...
            num2str(ophthalmologyTime,15));

        set_param( ...
            [mdl '/Human Reviewer'], ...
            'ServiceTimeFrom', ...
            'Dialog');

        set_param( ...
            [mdl '/Human Reviewer'], ...
            'ServiceTime', ...
            num2str(humanReviewTime,15));

        set_param( ...
            [mdl '/Recapture Preparation'], ...
            'ServiceTimeFrom', ...
            'Dialog');

        set_param( ...
            [mdl '/Recapture Preparation'], ...
            'ServiceTime', ...
            num2str(recapturePreparationTime,15));

        % ====================================================
        % 8K. CONFIGURE LOGGERS
        % ====================================================

        configureV7Loggers( ...
            mdl, ...
            cameraCount);

        % ====================================================
        % 8L. SIMULATION SETTINGS
        % ====================================================

        set_param( ...
            mdl, ...
            'StopTime', ...
            num2str(simulationTime));

        set_param( ...
            mdl, ...
            'Solver', ...
            'VariableStepDiscrete');

        set_param( ...
            mdl, ...
            'MaxStep', ...
            '1');

        % ====================================================
        % 8M. FINAL PRE-SIM REPAIR
        % ====================================================

        repairTracePipeline(mdl);

        removeDanglingLines(mdl);

        verifyCriticalFlow(mdl);

        set_param( ...
            mdl, ...
            'SimulationCommand', ...
            'update');

        % ====================================================
        % 8N. FINAL TRACE ROUTER INTEGRITY CHECK
        % ====================================================

        verifyBlockExists( ...
            [mdl '/TRACE Router'], ...
            'TRACE Router disappeared before simulation.');

        traceCriterion = get_param( ...
            [mdl '/TRACE Router'], ...
            'SwitchingCriterion');

        traceAttribute = get_param( ...
            [mdl '/TRACE Router'], ...
            'AttributeName');

        if ~strcmp( ...
                traceCriterion, ...
                'From attribute')

            error( ...
                'TRACE Router switching criterion corrupted.');

        end

        if ~strcmp( ...
                traceAttribute, ...
                'routeCode')

            error( ...
                'TRACE Router no longer uses routeCode.');

        end

        fprintf('TRACE Router final integrity: PASS\n');

        % ====================================================
        % 8O. SAVE WORKING MODEL
        % ====================================================

        save_system( ...
            mdl, ...
            workingModelFile);

        % ====================================================
        % 8P. CLEAR OUTPUT VARIABLES
        % ====================================================

        evalin( ...
            'base', ...
            ['clear ' ...
             'v7Route1 v7Route2 v7Route3 v7Route4 ' ...
             'v7RecaptureComplete ' ...
             'v7Cap1Wait v7Cap2Wait v7Cap3Wait ' ...
             'v7Cap1Util v7Cap2Util v7Cap3Util ' ...
             'v7AIWait v7OphWait v7HumanWait ' ...
             'v7AIUtil v7OphUtil v7HumanUtil']);

        % ====================================================
        % 8Q. RUN SIMULATION
        % ====================================================

        fprintf('\nRunning simulation...\n');

        simCommand = ...
            ['sim(''' mdl ''');'];

        evalin( ...
            'base', ...
            simCommand);

        fprintf('Simulation complete.\n');

        % ====================================================
        % 8R. READ TRACE ROUTE COUNTS
        % ====================================================

        routeCounts = ...
            zeros(1,4);

        for r = 1:4

            variableName = ...
                ['v7Route' num2str(r)];

            assertBaseVariable( ...
                variableName);

            routeCounts(r) = ...
                getLastMetric( ...
                    evalin( ...
                        'base', ...
                        variableName));

        end

        assertBaseVariable( ...
            'v7RecaptureComplete');

        recaptureComplete = ...
            getLastMetric( ...
                evalin( ...
                    'base', ...
                    'v7RecaptureComplete'));

        % ====================================================
        % 8S. READ CAMERA METRICS
        % ====================================================

        captureUtil = ...
            zeros(1,3);

        captureWait = ...
            zeros(1,3);

        for c = 1:cameraCount

            waitVariable = ...
                ['v7Cap' num2str(c) 'Wait'];

            utilVariable = ...
                ['v7Cap' num2str(c) 'Util'];

            assertBaseVariable( ...
                waitVariable);

            assertBaseVariable( ...
                utilVariable);

            captureWait(c) = ...
                getLastMetric( ...
                    evalin( ...
                        'base', ...
                        waitVariable));

            captureUtil(c) = ...
                getLastMetric( ...
                    evalin( ...
                        'base', ...
                        utilVariable));

        end

        % ====================================================
        % 8T. READ DOWNSTREAM METRICS
        % ====================================================

        assertBaseVariable( ...
            'v7AIUtil');

        assertBaseVariable( ...
            'v7OphUtil');

        assertBaseVariable( ...
            'v7HumanUtil');

        aiUtil = ...
            getLastMetric( ...
                evalin( ...
                    'base', ...
                    'v7AIUtil'));

        ophUtil = ...
            getLastMetric( ...
                evalin( ...
                    'base', ...
                    'v7OphUtil'));

        humanUtil = ...
            getLastMetric( ...
                evalin( ...
                    'base', ...
                    'v7HumanUtil'));

        % ====================================================
        % 8U. DERIVED METRICS
        % ====================================================

        expectedPrimary = ...
            floor( ...
                simulationTime ...
                / arrivalPeriod) ...
            + 1;

        primaryCompleted = ...
            sum(routeCounts) ...
            + recaptureComplete;

        primaryIncomplete = ...
            max( ...
                0, ...
                expectedPrimary ...
                - primaryCompleted);

        completionFraction = ...
            primaryCompleted ...
            / max(1,expectedPrimary);

        observedRecaptureFraction = ...
            recaptureComplete ...
            / max(1,primaryCompleted);

        observedPrimaryRate = ...
            primaryCompleted ...
            / simulationHours;

        annualizedPrimaryEquivalent = ...
            observedPrimaryRate ...
            * hoursPerDay ...
            * workingDays;

        maxCaptureUtil = ...
            max( ...
                captureUtil(1:cameraCount));

        maxCaptureWait = ...
            max( ...
                captureWait(1:cameraCount));

        maxDownstreamUtil = ...
            max( ...
                [aiUtil ...
                 ophUtil ...
                 humanUtil]);

        % ====================================================
        % 8V. THEORETICAL CAPTURE UTILIZATION
        % ====================================================

        theoreticalCaptureDemand = ...
            requiredPrimaryRate ...
            * (1 + recaptureFraction);

        totalNominalCaptureCapacity = ...
            cameraCount ...
            * captureCapacityPerStation;

        theoreticalAggregateCaptureUtil = ...
            theoreticalCaptureDemand ...
            / totalNominalCaptureCapacity;

        % ====================================================
        % 8W. FLOW-INTEGRITY CHECKS
        % ====================================================

        if primaryCompleted <= 0

            error( ...
                ['V7 FLOW INTEGRITY FAILURE: ' ...
                 'zero primary cases reached terminal outcomes.']);

        end

        % ----------------------------------------------------
        % Only enforce recapture completion if system is not
        % so overloaded that feedback entities cannot complete.
        %
        % For stable 2/3-camera scenarios, a nonzero requested
        % recapture fraction MUST produce recapture completions.
        % ----------------------------------------------------

        if recapturePercent > 0 && ...
                theoreticalAggregateCaptureUtil < 0.95 && ...
                recaptureComplete <= 0

            error( ...
                ['V7 RECAPTURE INTEGRITY FAILURE: ' ...
                 'requested recapture workload but zero ' ...
                 'recapture passes completed.']);

        end

        % ====================================================
        % 8X. ENGINEERING STABILITY RULE
        % ====================================================

        captureStable = ...
            maxCaptureUtil < 0.95;

        queueStable = ...
            maxCaptureWait < arrivalPeriod;

        downstreamStable = ...
            maxDownstreamUtil < 0.95;

        completionStable = ...
            completionFraction >= 0.98;

        stable = ...
            captureStable ...
            && queueStable ...
            && downstreamStable ...
            && completionStable;

        % ====================================================
        % 8Y. STORE RESULT
        % ====================================================

        M(scenarioIndex,:) = [ ...
            cameraCount, ...
            recapturePercent, ...
            theoreticalAggregateCaptureUtil, ...
            expectedPrimary, ...
            primaryCompleted, ...
            primaryIncomplete, ...
            completionFraction, ...
            recaptureComplete, ...
            observedRecaptureFraction*100, ...
            captureUtil(1), ...
            captureUtil(2), ...
            captureUtil(3), ...
            maxCaptureUtil, ...
            captureWait(1), ...
            captureWait(2), ...
            captureWait(3), ...
            maxCaptureWait, ...
            aiUtil, ...
            ophUtil, ...
            humanUtil, ...
            observedPrimaryRate, ...
            annualizedPrimaryEquivalent, ...
            double(stable)];

        % ====================================================
        % 8Z. PRINT SCENARIO RESULT
        % ====================================================

        fprintf('\n');
        fprintf('--- SCENARIO RESULT ---\n');

        fprintf( ...
            'Theoretical capture util : %.4f\n', ...
            theoreticalAggregateCaptureUtil);

        fprintf( ...
            'Simulated max cap util   : %.4f\n', ...
            maxCaptureUtil);

        fprintf( ...
            'Max capture wait         : %.3f s\n', ...
            maxCaptureWait);

        fprintf( ...
            'TRACE AI util            : %.4f\n', ...
            aiUtil);

        fprintf( ...
            'Ophthalmologist util     : %.4f\n', ...
            ophUtil);

        fprintf( ...
            'Human reviewer util      : %.4f\n', ...
            humanUtil);

        fprintf( ...
            'Primary complete         : %.0f / %.0f\n', ...
            primaryCompleted, ...
            expectedPrimary);

        fprintf( ...
            'Observed recapture       : %.2f %%\n', ...
            observedRecaptureFraction*100);

        fprintf( ...
            'Annualized primary eq.   : %.0f/year\n', ...
            annualizedPrimaryEquivalent);

        if stable

            fprintf( ...
                'STATUS                   : STABLE\n');

        else

            fprintf( ...
                'STATUS                   : CAPACITY PRESSURE\n');

        end

        % ====================================================
        % 8AA. SMOKE PARITY CHECK
        % ====================================================

        if SMOKE_ONLY

            fprintf('\n');
            fprintf('--- V6 PARITY SMOKE CHECK ---\n');

            smokeCompletionOK = ...
                completionFraction >= 0.98;

            smokeRecaptureOK = ...
                observedRecaptureFraction >= 0.17 ...
                && observedRecaptureFraction <= 0.23;

            smokeCaptureUtilOK = ...
                maxCaptureUtil >= 0.75 ...
                && maxCaptureUtil <= 0.90;

            smokeAIUtilOK = ...
                aiUtil >= 0.105 ...
                && aiUtil <= 0.15;

            fprintf( ...
                'Completion parity        : %d\n', ...
                smokeCompletionOK);

            fprintf( ...
                'Recapture parity         : %d\n', ...
                smokeRecaptureOK);

            fprintf( ...
                'Capture-util parity      : %d\n', ...
                smokeCaptureUtilOK);

            fprintf( ...
                'AI-util parity           : %d\n', ...
                smokeAIUtilOK);

            if ~( ...
                    smokeCompletionOK ...
                    && smokeRecaptureOK ...
                    && smokeCaptureUtilOK ...
                    && smokeAIUtilOK)

                error( ...
                    'V7 SMOKE TEST FAILED.');

            end

            fprintf('V7 SMOKE TEST: PASS\n');

        end

        % ====================================================
        % 8AB. SAVE REPRESENTATIVE 30%% MODEL
        % ====================================================
        %
        % IMPORTANT R2014a FIX:
        %
        % Do NOT:
        %
        %   save_system(mdl, representativeFile)
        %
        % That can cause the current model to become loaded under
        % the representative model name and later produce:
        %
        %   "model of same name is currently open"
        %
        % Instead:
        %
        %   save working model
        %   close any old representative model
        %   delete old representative file
        %   COPY working .mdl file
        % ====================================================

        if ~SMOKE_ONLY && ...
                recapturePercent == 30

            representativeModelName = sprintf( ...
                'NetraAI_DigitalTwin_V7_C%d_R30', ...
                cameraCount);

            representativeName = ...
                [representativeModelName '.mdl'];

            representativeFile = fullfile( ...
                modelDir, ...
                representativeName);

            % ------------------------------------------------
            % Save current working model first.
            % ------------------------------------------------

            save_system( ...
                mdl, ...
                workingModelFile);

            % ------------------------------------------------
            % Close old representative model if loaded.
            % ------------------------------------------------

            try

                close_system( ...
                    representativeModelName, ...
                    0);

            catch
            end

            % ------------------------------------------------
            % Delete old representative file.
            % ------------------------------------------------

            if exist( ...
                    representativeFile, ...
                    'file') == 2

                try
                    delete(representativeFile);
                catch
                end

            end

            % ------------------------------------------------
            % Copy working model file.
            % ------------------------------------------------

            [copyStatus,copyMessage] = copyfile( ...
                workingModelFile, ...
                representativeFile);

            if copyStatus ~= 1

                error( ...
                    ['Unable to save representative model: ' ...
                     copyMessage]);

            end

            fprintf( ...
                'Saved representative copy: %s\n', ...
                representativeName);

        end

        % ====================================================
        % 8AC. CLOSE SCENARIO
        % ====================================================

        try
            close_system(mdl,0);
        catch
        end

    end

end

% ============================================================
% 9. RESULT STRUCT
% ============================================================

results.version = ...
    'NETRAAI_V7_RESOURCE_SWEEP_FINAL_V3';

results.smokeOnly = ...
    SMOKE_ONLY;

results.provenance.annualTarget = ...
    'REQUIREMENT';

results.provenance.captureTime = ...
    'ASSUMPTION';

results.provenance.aiTime = ...
    'MEASURED_SINGLE_REFERENCE_CASE';

results.provenance.recapturePercentages = ...
    'ENGINEERING_SENSITIVITY_TEST';

results.provenance.routeDistribution = ...
    'DETERMINISTIC_ENGINEERING_TEST';

results.provenance.stabilityThresholds = ...
    'ENGINEERING_GUARDRAILS';

results.cameraCounts = ...
    cameraCounts;

results.recapturePercentages = ...
    recapturePercentages;

results.matrix = ...
    M;

results.columns = { ...
    'Cameras', ...
    'RecapturePct', ...
    'TheoreticalCaptureUtil', ...
    'PrimaryGenerated', ...
    'PrimaryCompleted', ...
    'PrimaryIncomplete', ...
    'CompletionFraction', ...
    'RecaptureCompleted', ...
    'ObservedRecapturePct', ...
    'Capture1Util', ...
    'Capture2Util', ...
    'Capture3Util', ...
    'MaxCaptureUtil', ...
    'Capture1WaitSec', ...
    'Capture2WaitSec', ...
    'Capture3WaitSec', ...
    'MaxCaptureWaitSec', ...
    'AIUtil', ...
    'OphUtil', ...
    'HumanUtil', ...
    'PrimaryRatePerHour', ...
    'AnnualizedPrimaryEq', ...
    'Stable'};

% ============================================================
% 10. PRINT RESOURCE-SIZING MATRIX
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' NETRAAI V7 RESOURCE-SIZING MATRIX\n');
fprintf('============================================================\n');

fprintf('\n');

fprintf( ...
    '%5s %7s %10s %10s %10s %11s %10s %10s\n', ...
    'Cams', ...
    'Recap%', ...
    'TheoryUtil', ...
    'SimUtil', ...
    'Wait(s)', ...
    'Complete', ...
    'AnnualEq', ...
    'Status');

fprintf( ...
    '%s\n', ...
    repmat('-',1,83));

for i = 1:size(M,1)

    if M(i,23) == 1

        statusText = ...
            'STABLE';

    else

        statusText = ...
            'PRESSURE';

    end

    fprintf( ...
        '%5.0f %7.0f %10.3f %10.3f %10.2f %4.0f/%-4.0f %10.0f %10s\n', ...
        M(i,1), ...
        M(i,2), ...
        M(i,3), ...
        M(i,13), ...
        M(i,17), ...
        M(i,5), ...
        M(i,4), ...
        M(i,22), ...
        statusText);

end

% ============================================================
% 11. MINIMUM TESTED CAMERA COUNT
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' MINIMUM TESTED CAPTURE RESOURCES\n');
fprintf('============================================================\n');

minCamera = zeros( ...
    1, ...
    length(recapturePercentages));

for r = 1:length(recapturePercentages)

    pct = ...
        recapturePercentages(r);

    rows = find( ...
        M(:,2) == pct);

    stableRows = rows( ...
        M(rows,23) == 1);

    if isempty(stableRows)

        minCamera(r) = 0;

        fprintf( ...
            '%2.0f%% recapture : >%d camera(s) / unresolved\n', ...
            pct, ...
            max(cameraCounts));

    else

        minCamera(r) = ...
            min( ...
                M(stableRows,1));

        fprintf( ...
            '%2.0f%% recapture : %d camera(s)\n', ...
            pct, ...
            minCamera(r));

    end

end

results.minimumCameraCount = ...
    minCamera;

% ============================================================
% 12. OUTPUT FILENAMES
% ============================================================

if SMOKE_ONLY

    matFile = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_Smoke_Result.mat');

    csvFile = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_Smoke.csv');

    reportFile = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_Smoke_Report.txt');

else

    matFile = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_ResourceSweep_Result.mat');

    csvFile = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_ResourceSweep.csv');

    reportFile = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_ResourceSweep_Report.txt');

end

% ============================================================
% 13. SAVE MAT RESULT
% ============================================================

save( ...
    matFile, ...
    'results');

% ============================================================
% 14. SAVE CSV
% ============================================================

fid = fopen( ...
    csvFile, ...
    'w');

if fid == -1

    error( ...
        'Unable to create V7 CSV output.');

end

fprintf(fid, ...
    ['Cameras,' ...
     'RecapturePct,' ...
     'TheoreticalCaptureUtil,' ...
     'PrimaryGenerated,' ...
     'PrimaryCompleted,' ...
     'PrimaryIncomplete,' ...
     'CompletionFraction,' ...
     'RecaptureCompleted,' ...
     'ObservedRecapturePct,' ...
     'Capture1Util,' ...
     'Capture2Util,' ...
     'Capture3Util,' ...
     'MaxCaptureUtil,' ...
     'Capture1WaitSec,' ...
     'Capture2WaitSec,' ...
     'Capture3WaitSec,' ...
     'MaxCaptureWaitSec,' ...
     'AIUtil,' ...
     'OphUtil,' ...
     'HumanUtil,' ...
     'PrimaryRatePerHour,' ...
     'AnnualizedPrimaryEq,' ...
     'Stable\n']);

for i = 1:size(M,1)

    fprintf(fid, ...
        ['%.0f,%.0f,%.8f,%.0f,%.0f,%.0f,' ...
         '%.8f,%.0f,%.8f,' ...
         '%.8f,%.8f,%.8f,%.8f,' ...
         '%.8f,%.8f,%.8f,%.8f,' ...
         '%.8f,%.8f,%.8f,' ...
         '%.8f,%.4f,%.0f\n'], ...
        M(i,1), ...
        M(i,2), ...
        M(i,3), ...
        M(i,4), ...
        M(i,5), ...
        M(i,6), ...
        M(i,7), ...
        M(i,8), ...
        M(i,9), ...
        M(i,10), ...
        M(i,11), ...
        M(i,12), ...
        M(i,13), ...
        M(i,14), ...
        M(i,15), ...
        M(i,16), ...
        M(i,17), ...
        M(i,18), ...
        M(i,19), ...
        M(i,20), ...
        M(i,21), ...
        M(i,22), ...
        M(i,23));

end

fclose(fid);

% ============================================================
% 15. SAVE TEXT REPORT
% ============================================================

fid = fopen( ...
    reportFile, ...
    'w');

if fid ~= -1

    fprintf(fid, ...
        'ANEYE / NetraAI Digital Twin V7\n');

    fprintf(fid, ...
        'District Resource-Sizing Stress Sweep\n\n');

    fprintf(fid, ...
        'Annual target: %.0f/year [REQUIREMENT]\n', ...
        annualTarget);

    fprintf(fid, ...
        'Working days: %.0f/year [ASSUMPTION]\n', ...
        workingDays);

    fprintf(fid, ...
        'Operating hours: %.0f/day [ASSUMPTION]\n', ...
        hoursPerDay);

    fprintf(fid, ...
        'Capture service: %.2f s [ASSUMPTION]\n', ...
        captureTime);

    fprintf(fid, ...
        'AI service: %.5f s [MEASURED_SINGLE_REFERENCE_CASE]\n', ...
        aiTime);

    fprintf(fid, ...
        'Recapture range: 0-30%% [ENGINEERING SENSITIVITY TEST]\n');

    fprintf(fid, ...
        'Capture stability guardrail: <95%% utilization\n');

    fprintf(fid, ...
        'Completion guardrail: >=98%% in 8-hour horizon\n\n');

    fprintf(fid, ...
        ['Cams Recap TheoryUtil SimUtil MaxWait ' ...
         'Completed Generated AnnualEq Stable\n']);

    for i = 1:size(M,1)

        fprintf(fid, ...
            ['%.0f %.0f %.6f %.6f %.4f ' ...
             '%.0f %.0f %.0f %.0f\n'], ...
            M(i,1), ...
            M(i,2), ...
            M(i,3), ...
            M(i,13), ...
            M(i,17), ...
            M(i,5), ...
            M(i,4), ...
            M(i,22), ...
            M(i,23));

    end

    fprintf(fid, ...
        '\nMinimum tested capture resources:\n');

    for r = 1:length(recapturePercentages)

        if minCamera(r) == 0

            fprintf(fid, ...
                '%2.0f%% -> >%d / unresolved\n', ...
                recapturePercentages(r), ...
                max(cameraCounts));

        else

            fprintf(fid, ...
                '%2.0f%% -> %d camera(s)\n', ...
                recapturePercentages(r), ...
                minCamera(r));

        end

    end

    fclose(fid);

end

% ============================================================
% 16. PLOT CAPTURE UTILIZATION
% ============================================================

if ~SMOKE_ONLY

    figure( ...
        'Name', ...
        'NetraAI V7 Capture Utilization');

    hold on

    legendEntries = {};

    for c = 1:length(cameraCounts)

        rows = find( ...
            M(:,1) == cameraCounts(c));

        plot( ...
            M(rows,2), ...
            M(rows,13), ...
            '-o', ...
            'LineWidth', ...
            1.5);

        legendEntries{end+1} = sprintf( ...
            '%d Capture Station(s)', ...
            cameraCounts(c));

    end

    plot( ...
        [min(recapturePercentages) ...
         max(recapturePercentages)], ...
        [0.95 0.95], ...
        '--', ...
        'LineWidth', ...
        1.2);

    legendEntries{end+1} = ...
        '95% Engineering Guardrail';

    xlabel( ...
        'Recapture workload (%)');

    ylabel( ...
        'Maximum capture utilization');

    title( ...
        'NetraAI V7 - Capture Utilization vs Recapture Workload');

    legend( ...
        legendEntries, ...
        'Location', ...
        'NorthWest');

    grid on

    hold off

    utilPlot = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_CaptureUtilization.png');

    saveas( ...
        gcf, ...
        utilPlot);

    close(gcf);

else

    utilPlot = '';

end

% ============================================================
% 17. PLOT CAPTURE WAIT
% ============================================================

if ~SMOKE_ONLY

    figure( ...
        'Name', ...
        'NetraAI V7 Capture Wait');

    hold on

    legendEntries = {};

    for c = 1:length(cameraCounts)

        rows = find( ...
            M(:,1) == cameraCounts(c));

        plot( ...
            M(rows,2), ...
            M(rows,17), ...
            '-o', ...
            'LineWidth', ...
            1.5);

        legendEntries{end+1} = sprintf( ...
            '%d Capture Station(s)', ...
            cameraCounts(c));

    end

    xlabel( ...
        'Recapture workload (%)');

    ylabel( ...
        'Maximum average capture queue wait (s)');

    title( ...
        'NetraAI V7 - Capture Queue Delay vs Recapture Workload');

    legend( ...
        legendEntries, ...
        'Location', ...
        'NorthWest');

    grid on

    hold off

    waitPlot = fullfile( ...
        resultsDir, ...
        'NetraAI_V7_CaptureWait.png');

    saveas( ...
        gcf, ...
        waitPlot);

    close(gcf);

else

    waitPlot = '';

end

% ============================================================
% 18. FINAL OUTPUT
% ============================================================

fprintf('\n');
fprintf('============================================================\n');

if SMOKE_ONLY

    fprintf(' V7 CORRECTED SMOKE TEST COMPLETE\n');

else

    fprintf(' V7 CORRECTED RESOURCE SWEEP COMPLETE\n');

end

fprintf('============================================================\n');

fprintf('\nMAT result:\n%s\n', ...
    matFile);

fprintf('\nCSV result:\n%s\n', ...
    csvFile);

fprintf('\nText report:\n%s\n', ...
    reportFile);

if ~isempty(utilPlot)

    fprintf('\nUtilization plot:\n%s\n', ...
        utilPlot);

end

if ~isempty(waitPlot)

    fprintf('\nWait plot:\n%s\n', ...
        waitPlot);

end

if ~SMOKE_ONLY

    fprintf('\nRepresentative models:\n');

    for c = 1:length(cameraCounts)

        fprintf( ...
            'NetraAI_DigitalTwin_V7_C%d_R30.mdl\n', ...
            cameraCounts(c));

    end

end

fprintf('============================================================\n');

end


% ============================================================
% BUILD 20-POSITION TRACE ROUTE SEQUENCE
% ============================================================

function sequence = buildRouteSequence20( ...
    recaptureSlots)

if recaptureSlots < 0 || ...
        recaptureSlots > 20

    error( ...
        'recaptureSlots must be between 0 and 20.');

end

sequence = ...
    zeros(1,20);

recapturePositions = [];

% ------------------------------------------------------------
% Spread recapture slots approximately evenly.
% ------------------------------------------------------------

if recaptureSlots > 0

    for k = 1:recaptureSlots

        pos = round( ...
            ((k - 0.5) * 20) ...
            / recaptureSlots);

        pos = max( ...
            1, ...
            min(20,pos));

        while any( ...
                recapturePositions == pos)

            pos = ...
                pos + 1;

            if pos > 20
                pos = 1;
            end

        end

        recapturePositions(end+1) = ...
            pos;

    end

end

% ------------------------------------------------------------
% Remaining slots cycle through TRACE routes 1-4.
% ------------------------------------------------------------

normalIndex = 1;

for i = 1:20

    if any( ...
            recapturePositions == i)

        sequence(i) = 5;

    else

        sequence(i) = ...
            mod( ...
                normalIndex - 1, ...
                4) ...
            + 1;

        normalIndex = ...
            normalIndex + 1;

    end

end

end


% ============================================================
% CONFIGURE PRIMARY TRACE POPULATION
% ============================================================

function configureRoutePopulation( ...
    mdl, ...
    routeSequence)

fprintf('\nRebuilding deterministic V7 primary population...\n');

patientArrival = ...
    [mdl '/Patient Arrival'];

primaryFlowSetter = ...
    [mdl '/Set Primary Flow'];

traceRouter = ...
    [mdl '/TRACE Router'];

% ------------------------------------------------------------
% TRACE Router MUST survive.
% ------------------------------------------------------------

verifyBlockExists( ...
    traceRouter, ...
    'TRACE Router missing before population rebuild.');

% ------------------------------------------------------------
% Delete V6 primary population split/merge blocks.
% ------------------------------------------------------------

oldSplitter = ...
    [mdl '/Balanced TRACE Class Splitter'];

oldPopulationMerger = ...
    [mdl '/Population Merger'];

try
    delete_block(oldSplitter);
catch
end

try
    delete_block(oldPopulationMerger);
catch
end

% ------------------------------------------------------------
% Delete old routeCode Set Attribute blocks.
%
% CRITICAL:
% NEVER DELETE TRACE ROUTER.
% ------------------------------------------------------------

blocks = find_system( ...
    mdl, ...
    'SearchDepth', ...
    1, ...
    'Type', ...
    'Block');

for k = 1:length(blocks)

    blockPath = ...
        blocks{k};

    if strcmp( ...
            blockPath, ...
            traceRouter)

        continue;

    end

    try

        attrName = get_param( ...
            blockPath, ...
            'AttributeName');

        if strcmp( ...
                attrName, ...
                'routeCode')

            delete_block( ...
                blockPath);

        end

    catch
    end

end

verifyBlockExists( ...
    traceRouter, ...
    ['CRITICAL: TRACE Router was deleted while ' ...
     'removing routeCode setter blocks.']);

fprintf('TRACE Router preserved: PASS\n');

% ------------------------------------------------------------
% Create 20-output Round Robin splitter.
% ------------------------------------------------------------

splitter = ...
    [mdl '/V7 TRACE Scenario Splitter'];

try
    delete_block(splitter);
catch
end

add_block( ...
    'simeventslib/Routing/Output Switch', ...
    splitter, ...
    'Position', ...
    [275 70 410 1180]);

set_param( ...
    splitter, ...
    'NumberOutputPorts', ...
    '20');

set_param( ...
    splitter, ...
    'SwitchingCriterion', ...
    'Round robin');

% ------------------------------------------------------------
% Path Combiner for 20 primary paths.
% ------------------------------------------------------------

populationCombiner = ...
    [mdl '/V7 Population Combiner'];

try
    delete_block(populationCombiner);
catch
end

add_block( ...
    'simeventslib/Routing/Path Combiner', ...
    populationCombiner, ...
    'Position', ...
    [720 70 855 1180]);

set_param( ...
    populationCombiner, ...
    'NumberInputPorts', ...
    '20');

set_param( ...
    populationCombiner, ...
    'InputPortPrecedence', ...
    'IN1 port');

set_param( ...
    populationCombiner, ...
    'SpecifyEventPriority', ...
    'off');

% ------------------------------------------------------------
% Arrival -> deterministic splitter.
% ------------------------------------------------------------

forceEntityConnection( ...
    mdl, ...
    patientArrival, ...
    splitter);

% ------------------------------------------------------------
% Create twenty routeCode setters.
% ------------------------------------------------------------

for i = 1:20

    setter = [ ...
        mdl ...
        '/V7 Route Slot ' ...
        num2str(i)];

    try
        delete_block(setter);
    catch
    end

    y = ...
        80 + (i-1)*52;

    add_block( ...
        'simeventslib/Attributes/Set Attribute', ...
        setter, ...
        'Position', ...
        [475 y 620 y+35]);

    set_param( ...
        setter, ...
        'AttributeName', ...
        'routeCode');

    set_param( ...
        setter, ...
        'AttributeFrom', ...
        'Dialog');

    set_param( ...
        setter, ...
        'AttributeValue', ...
        num2str(routeSequence(i)));

    set_param( ...
        setter, ...
        'AttributeCreate', ...
        'on');

    forceEntityOutputConnection( ...
        mdl, ...
        splitter, ...
        setter, ...
        i);

    forceEntityToInputConnection( ...
        mdl, ...
        setter, ...
        populationCombiner, ...
        i);

end

% ------------------------------------------------------------
% Combined primary traffic -> flowType=1 setter.
% ------------------------------------------------------------

forceEntityConnection( ...
    mdl, ...
    populationCombiner, ...
    primaryFlowSetter);

verifyBlockExists( ...
    traceRouter, ...
    'TRACE Router missing after route population build.');

fprintf('Deterministic V7 primary population: PASS\n');

end


% ============================================================
% REPAIR TRACE / RECAPTURE PIPELINE
% ============================================================

function repairTracePipeline(mdl)

fprintf('Repairing TRACE downstream topology...\n');

primaryFlowSetter = ...
    [mdl '/Set Primary Flow'];

acquisitionCombiner = ...
    [mdl '/Acquisition Path Combiner'];

postAIRouter = ...
    [mdl '/Post AI Flow Router'];

traceRouter = ...
    [mdl '/TRACE Router'];

routineSink = ...
    [mdl '/1 ROUTINE'];

ophQueue = ...
    [mdl '/Ophthalmology Queue'];

humanQueue = ...
    [mdl '/Human Review Queue'];

reviewRecaptureSink = ...
    [mdl '/4 REVIEW RECAPTURE'];

recapturePreparation = ...
    [mdl '/Recapture Preparation'];

recaptureFlowSetter = ...
    [mdl '/Set Recapture Flow'];

recaptureCompleteSink = ...
    [mdl '/RECAPTURE COMPLETE'];

requiredBlocks = { ...
    primaryFlowSetter, ...
    acquisitionCombiner, ...
    postAIRouter, ...
    traceRouter, ...
    routineSink, ...
    ophQueue, ...
    humanQueue, ...
    reviewRecaptureSink, ...
    recapturePreparation, ...
    recaptureFlowSetter, ...
    recaptureCompleteSink};

for k = 1:length(requiredBlocks)

    verifyBlockExists( ...
        requiredBlocks{k}, ...
        ['Missing flow block: ' ...
         requiredBlocks{k}]);

end

% ------------------------------------------------------------
% Primary -> acquisition input 1
% ------------------------------------------------------------

forceEntityToInputConnection( ...
    mdl, ...
    primaryFlowSetter, ...
    acquisitionCombiner, ...
    1);

% ------------------------------------------------------------
% Recapture -> acquisition input 2
% ------------------------------------------------------------

forceEntityToInputConnection( ...
    mdl, ...
    recaptureFlowSetter, ...
    acquisitionCombiner, ...
    2);

% ------------------------------------------------------------
% Primary AI pass -> TRACE
% ------------------------------------------------------------

forceEntityOutputConnection( ...
    mdl, ...
    postAIRouter, ...
    traceRouter, ...
    1);

% ------------------------------------------------------------
% Recapture AI pass -> complete
% ------------------------------------------------------------

forceEntityOutputConnection( ...
    mdl, ...
    postAIRouter, ...
    recaptureCompleteSink, ...
    2);

% ------------------------------------------------------------
% TRACE routes 1-5
% ------------------------------------------------------------

forceEntityOutputConnection( ...
    mdl, ...
    traceRouter, ...
    routineSink, ...
    1);

forceEntityOutputConnection( ...
    mdl, ...
    traceRouter, ...
    ophQueue, ...
    2);

forceEntityOutputConnection( ...
    mdl, ...
    traceRouter, ...
    humanQueue, ...
    3);

forceEntityOutputConnection( ...
    mdl, ...
    traceRouter, ...
    reviewRecaptureSink, ...
    4);

forceEntityOutputConnection( ...
    mdl, ...
    traceRouter, ...
    recapturePreparation, ...
    5);

% ------------------------------------------------------------
% Recapture prep -> flowType=2
% ------------------------------------------------------------

forceEntityConnection( ...
    mdl, ...
    recapturePreparation, ...
    recaptureFlowSetter);

% ------------------------------------------------------------
% Router semantic checks.
% ------------------------------------------------------------

traceCriterion = get_param( ...
    traceRouter, ...
    'SwitchingCriterion');

traceAttribute = get_param( ...
    traceRouter, ...
    'AttributeName');

if ~strcmp( ...
        traceCriterion, ...
        'From attribute')

    error( ...
        'TRACE Router must use From attribute.');

end

if ~strcmp( ...
        traceAttribute, ...
        'routeCode')

    error( ...
        'TRACE Router must use routeCode.');

end

postCriterion = get_param( ...
    postAIRouter, ...
    'SwitchingCriterion');

postAttribute = get_param( ...
    postAIRouter, ...
    'AttributeName');

if ~strcmp( ...
        postCriterion, ...
        'From attribute')

    error( ...
        'Post AI Flow Router must use From attribute.');

end

if ~strcmp( ...
        postAttribute, ...
        'flowType')

    error( ...
        'Post AI Flow Router must use flowType.');

end

fprintf('TRACE downstream topology: PASS\n');

end


% ============================================================
% CONFIGURE CAPTURE RESOURCES
% ============================================================

function configureCaptureResources( ...
    mdl, ...
    cameraCount, ...
    captureTime)

fprintf( ...
    'Configuring %d capture station(s)...\n', ...
    cameraCount);

if cameraCount < 1 || ...
        cameraCount > 3

    error( ...
        'V7 supports only 1, 2, or 3 capture stations.');

end

acquisitionCombiner = ...
    [mdl '/Acquisition Path Combiner'];

loadBalancer = ...
    [mdl '/Capture Load Balancer'];

queue1 = ...
    [mdl '/Capture Queue'];

server1 = ...
    [mdl '/Fundus Capture'];

queue2 = ...
    [mdl '/Capture Queue 2'];

server2 = ...
    [mdl '/Fundus Capture 2'];

oldCaptureMerger = ...
    [mdl '/Capture Merger'];

aiQueue = ...
    [mdl '/AI Queue'];

queue2WaitLogger = ...
    [mdl '/Metric Capture2 Wait'];

server2UtilLogger = ...
    [mdl '/Metric Capture2 Util'];

% ------------------------------------------------------------
% Camera 1 service time.
% ------------------------------------------------------------

set_param( ...
    server1, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    server1, ...
    'ServiceTime', ...
    num2str(captureTime,15));

% ============================================================
% ONE CAMERA
% ============================================================

if cameraCount == 1

    try
        delete_block(queue2WaitLogger);
    catch
    end

    try
        delete_block(server2UtilLogger);
    catch
    end

    try
        delete_block(queue2);
    catch
    end

    try
        delete_block(server2);
    catch
    end

    try
        delete_block(loadBalancer);
    catch
    end

    try
        delete_block(oldCaptureMerger);
    catch
    end

    forceEntityConnection( ...
        mdl, ...
        acquisitionCombiner, ...
        queue1);

    forceEntityConnection( ...
        mdl, ...
        queue1, ...
        server1);

    forceEntityConnection( ...
        mdl, ...
        server1, ...
        aiQueue);

    fprintf('One-camera capture topology: PASS\n');

    return;

end

% ============================================================
% TWO / THREE CAMERA COMMON CONFIGURATION
% ============================================================

set_param( ...
    server2, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    server2, ...
    'ServiceTime', ...
    num2str(captureTime,15));

% ------------------------------------------------------------
% Replace inherited capture merger with Path Combiner.
% ------------------------------------------------------------

try
    delete_block(oldCaptureMerger);
catch
end

captureCombiner = ...
    [mdl '/Capture Merger'];

add_block( ...
    'simeventslib/Routing/Path Combiner', ...
    captureCombiner, ...
    'Position', ...
    [1230 175 1360 405]);

set_param( ...
    captureCombiner, ...
    'NumberInputPorts', ...
    num2str(cameraCount));

set_param( ...
    captureCombiner, ...
    'InputPortPrecedence', ...
    'IN1 port');

set_param( ...
    captureCombiner, ...
    'SpecifyEventPriority', ...
    'off');

% ------------------------------------------------------------
% Capture load balancer.
% ------------------------------------------------------------

set_param( ...
    loadBalancer, ...
    'NumberOutputPorts', ...
    num2str(cameraCount));

set_param( ...
    loadBalancer, ...
    'SwitchingCriterion', ...
    'Round robin');

forceEntityConnection( ...
    mdl, ...
    acquisitionCombiner, ...
    loadBalancer);

% ------------------------------------------------------------
% Camera 1
% ------------------------------------------------------------

forceEntityOutputConnection( ...
    mdl, ...
    loadBalancer, ...
    queue1, ...
    1);

forceEntityConnection( ...
    mdl, ...
    queue1, ...
    server1);

forceEntityToInputConnection( ...
    mdl, ...
    server1, ...
    captureCombiner, ...
    1);

% ------------------------------------------------------------
% Camera 2
% ------------------------------------------------------------

forceEntityOutputConnection( ...
    mdl, ...
    loadBalancer, ...
    queue2, ...
    2);

forceEntityConnection( ...
    mdl, ...
    queue2, ...
    server2);

forceEntityToInputConnection( ...
    mdl, ...
    server2, ...
    captureCombiner, ...
    2);

% ============================================================
% THREE CAMERAS
% ============================================================

if cameraCount == 3

    queue3 = ...
        [mdl '/Capture Queue 3'];

    server3 = ...
        [mdl '/Fundus Capture 3'];

    try
        delete_block(queue3);
    catch
    end

    try
        delete_block(server3);
    catch
    end

    add_block( ...
        'simeventslib/Queues/FIFO Queue', ...
        queue3, ...
        'Position', ...
        [900 440 1000 490]);

    set_param( ...
        queue3, ...
        'Capacity', ...
        '1000');

    set_param( ...
        queue3, ...
        'StatAverageWait', ...
        'on');

    add_block( ...
        'simeventslib/Servers/Single Server', ...
        server3, ...
        'Position', ...
        [1050 440 1180 490]);

    set_param( ...
        server3, ...
        'ServiceTimeFrom', ...
        'Dialog');

    set_param( ...
        server3, ...
        'ServiceTime', ...
        num2str(captureTime,15));

    set_param( ...
        server3, ...
        'StatUtilization', ...
        'on');

    forceEntityOutputConnection( ...
        mdl, ...
        loadBalancer, ...
        queue3, ...
        3);

    forceEntityConnection( ...
        mdl, ...
        queue3, ...
        server3);

    forceEntityToInputConnection( ...
        mdl, ...
        server3, ...
        captureCombiner, ...
        3);

end

% ------------------------------------------------------------
% Combined capture output -> AI.
% ------------------------------------------------------------

forceEntityConnection( ...
    mdl, ...
    captureCombiner, ...
    aiQueue);

% ------------------------------------------------------------
% Generate any new statistic ports.
% ------------------------------------------------------------

set_param( ...
    mdl, ...
    'SimulationCommand', ...
    'update');

% ============================================================
% CAMERA 3 LOGGERS
% ============================================================

if cameraCount == 3

    queue3 = ...
        [mdl '/Capture Queue 3'];

    server3 = ...
        [mdl '/Fundus Capture 3'];

    queueLogger = ...
        [mdl '/Metric Capture3 Wait'];

    utilLogger = ...
        [mdl '/Metric Capture3 Util'];

    try
        delete_block(queueLogger);
    catch
    end

    try
        delete_block(utilLogger);
    catch
    end

    % --------------------------------------------------------
    % Camera 3 queue wait.
    % --------------------------------------------------------

    add_block( ...
        'simulink/Sinks/To Workspace', ...
        queueLogger, ...
        'VariableName', ...
        'v7Cap3Wait', ...
        'SaveFormat', ...
        'Array', ...
        'Position', ...
        [1210 445 1360 480]);

    queuePorts = get_param( ...
        queue3, ...
        'PortHandles');

    queueLoggerPorts = get_param( ...
        queueLogger, ...
        'PortHandles');

    if isempty(queuePorts.Outport)

        error( ...
            'Capture Queue 3 wait statistic output missing.');

    end

    add_line( ...
        mdl, ...
        queuePorts.Outport(1), ...
        queueLoggerPorts.Inport(1), ...
        'autorouting', ...
        'on');

    % --------------------------------------------------------
    % Camera 3 utilization.
    % --------------------------------------------------------

    add_block( ...
        'simulink/Sinks/To Workspace', ...
        utilLogger, ...
        'VariableName', ...
        'v7Cap3Util', ...
        'SaveFormat', ...
        'Array', ...
        'Position', ...
        [1210 495 1360 530]);

    serverPorts = get_param( ...
        server3, ...
        'PortHandles');

    utilLoggerPorts = get_param( ...
        utilLogger, ...
        'PortHandles');

    if isempty(serverPorts.Outport)

        error( ...
            'Fundus Capture 3 utilization output missing.');

    end

    add_line( ...
        mdl, ...
        serverPorts.Outport(1), ...
        utilLoggerPorts.Inport(1), ...
        'autorouting', ...
        'on');

end

fprintf( ...
    '%d-camera capture topology: PASS\n', ...
    cameraCount);

end


% ============================================================
% VERIFY CRITICAL FLOW
% ============================================================

function verifyCriticalFlow(mdl)

fprintf('Validating critical V7 flow...\n');

requiredBlocks = { ...
    [mdl '/Set Primary Flow'], ...
    [mdl '/Acquisition Path Combiner'], ...
    [mdl '/AI Queue'], ...
    [mdl '/TRACE AI Processing'], ...
    [mdl '/Post AI Flow Router'], ...
    [mdl '/TRACE Router'], ...
    [mdl '/1 ROUTINE'], ...
    [mdl '/Ophthalmology Queue'], ...
    [mdl '/Human Review Queue'], ...
    [mdl '/4 REVIEW RECAPTURE'], ...
    [mdl '/Recapture Preparation'], ...
    [mdl '/Set Recapture Flow'], ...
    [mdl '/RECAPTURE COMPLETE']};

for k = 1:length(requiredBlocks)

    verifyBlockExists( ...
        requiredBlocks{k}, ...
        ['Missing critical block: ' ...
         requiredBlocks{k}]);

end

verifyEntityInputConnected( ...
    [mdl '/Set Primary Flow']);

verifyEntityInputConnected( ...
    [mdl '/Acquisition Path Combiner']);

verifyEntityInputConnected( ...
    [mdl '/AI Queue']);

verifyEntityInputConnected( ...
    [mdl '/TRACE AI Processing']);

verifyEntityInputConnected( ...
    [mdl '/Post AI Flow Router']);

verifyEntityInputConnected( ...
    [mdl '/TRACE Router']);

verifyEntityInputConnected( ...
    [mdl '/1 ROUTINE']);

verifyEntityInputConnected( ...
    [mdl '/Ophthalmology Queue']);

verifyEntityInputConnected( ...
    [mdl '/Human Review Queue']);

verifyEntityInputConnected( ...
    [mdl '/4 REVIEW RECAPTURE']);

verifyEntityInputConnected( ...
    [mdl '/Recapture Preparation']);

verifyEntityInputConnected( ...
    [mdl '/Set Recapture Flow']);

verifyEntityInputConnected( ...
    [mdl '/RECAPTURE COMPLETE']);

fprintf('Critical V7 flow validation: PASS\n');

end


% ============================================================
% CONFIGURE OUTPUT LOGGERS
% ============================================================

function configureV7Loggers( ...
    mdl, ...
    cameraCount)

setLoggerIfExists( ...
    mdl, ...
    'Route 1 Count', ...
    'v7Route1');

setLoggerIfExists( ...
    mdl, ...
    'Route 2 Count', ...
    'v7Route2');

setLoggerIfExists( ...
    mdl, ...
    'Route 3 Count', ...
    'v7Route3');

setLoggerIfExists( ...
    mdl, ...
    'Route 4 Count', ...
    'v7Route4');

setLoggerIfExists( ...
    mdl, ...
    'Recapture Complete Count', ...
    'v7RecaptureComplete');

% ------------------------------------------------------------
% Capture 1
% ------------------------------------------------------------

setLoggerIfExists( ...
    mdl, ...
    'Metric Queue 1', ...
    'v7Cap1Wait');

setLoggerIfExists( ...
    mdl, ...
    'Metric Util 1', ...
    'v7Cap1Util');

% ------------------------------------------------------------
% Capture 2
% ------------------------------------------------------------

if cameraCount >= 2

    setLoggerIfExists( ...
        mdl, ...
        'Metric Capture2 Wait', ...
        'v7Cap2Wait');

    setLoggerIfExists( ...
        mdl, ...
        'Metric Capture2 Util', ...
        'v7Cap2Util');

end

% ------------------------------------------------------------
% Capture 3
% ------------------------------------------------------------

if cameraCount == 3

    setLoggerIfExists( ...
        mdl, ...
        'Metric Capture3 Wait', ...
        'v7Cap3Wait');

    setLoggerIfExists( ...
        mdl, ...
        'Metric Capture3 Util', ...
        'v7Cap3Util');

end

% ------------------------------------------------------------
% AI / review
% ------------------------------------------------------------

setLoggerIfExists( ...
    mdl, ...
    'Metric Queue 2', ...
    'v7AIWait');

setLoggerIfExists( ...
    mdl, ...
    'Metric Queue 3', ...
    'v7OphWait');

setLoggerIfExists( ...
    mdl, ...
    'Metric Queue 4', ...
    'v7HumanWait');

setLoggerIfExists( ...
    mdl, ...
    'Metric Util 2', ...
    'v7AIUtil');

setLoggerIfExists( ...
    mdl, ...
    'Metric Util 3', ...
    'v7OphUtil');

setLoggerIfExists( ...
    mdl, ...
    'Metric Util 4', ...
    'v7HumanUtil');

end


% ============================================================
% SET LOGGER VARIABLE
% ============================================================

function setLoggerIfExists( ...
    mdl, ...
    blockName, ...
    variableName)

blockPath = ...
    [mdl '/' blockName];

try

    get_param( ...
        blockPath, ...
        'Handle');

catch

    error( ...
        ['Required logger missing: ' ...
         blockPath]);

end

set_param( ...
    blockPath, ...
    'VariableName', ...
    variableName);

end


% ============================================================
% REMOVE DANGLING GRAPHICAL LINES
% ============================================================

function removeDanglingLines(mdl)

lines = find_system( ...
    mdl, ...
    'FindAll', ...
    'on', ...
    'Type', ...
    'line');

removed = 0;

for k = 1:length(lines)

    try

        src = get_param( ...
            lines(k), ...
            'SrcPortHandle');

        dst = get_param( ...
            lines(k), ...
            'DstPortHandle');

        badSource = ...
            isempty(src) || ...
            all(src == -1);

        badDestination = ...
            isempty(dst) || ...
            all(dst == -1);

        if badSource || ...
                badDestination

            delete_line( ...
                lines(k));

            removed = ...
                removed + 1;

        end

    catch
    end

end

fprintf( ...
    'Dangling graphical lines removed: %d\n', ...
    removed);

end


% ============================================================
% VERIFY BLOCK EXISTS
% ============================================================

function verifyBlockExists( ...
    blockPath, ...
    errorMessage)

try

    get_param( ...
        blockPath, ...
        'Handle');

catch

    error(errorMessage);

end

end


% ============================================================
% ASSERT BASE WORKSPACE VARIABLE
% ============================================================

function assertBaseVariable( ...
    variableName)

existsFlag = evalin( ...
    'base', ...
    ['exist(''' ...
     variableName ...
     ''',''var'')']);

if existsFlag ~= 1

    error( ...
        ['Missing V7 simulation output: ' ...
         variableName]);

end

end


% ============================================================
% FORCE STANDARD ENTITY CONNECTION
% ============================================================

function forceEntityConnection( ...
    model, ...
    source, ...
    destination)

srcHandles = get_param( ...
    source, ...
    'PortHandles');

dstHandles = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput( ...
    srcHandles, ...
    1);

dstPort = getEntityInput( ...
    dstHandles, ...
    1);

disconnectPortLine( ...
    srcPort);

disconnectPortLine( ...
    dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% FORCE SPECIFIC ENTITY OUTPUT CONNECTION
% ============================================================

function forceEntityOutputConnection( ...
    model, ...
    source, ...
    destination, ...
    outputIndex)

srcHandles = get_param( ...
    source, ...
    'PortHandles');

dstHandles = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput( ...
    srcHandles, ...
    outputIndex);

dstPort = getEntityInput( ...
    dstHandles, ...
    1);

disconnectPortLine( ...
    srcPort);

disconnectPortLine( ...
    dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% FORCE SPECIFIC ENTITY INPUT CONNECTION
% ============================================================

function forceEntityToInputConnection( ...
    model, ...
    source, ...
    destination, ...
    inputIndex)

srcHandles = get_param( ...
    source, ...
    'PortHandles');

dstHandles = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput( ...
    srcHandles, ...
    1);

dstPort = getEntityInput( ...
    dstHandles, ...
    inputIndex);

disconnectPortLine( ...
    srcPort);

disconnectPortLine( ...
    dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% DISCONNECT LINE FROM PORT
% ============================================================

function disconnectPortLine( ...
    portHandle)

if isempty(portHandle)
    return;
end

try

    lineHandle = get_param( ...
        portHandle, ...
        'Line');

    if ~isempty(lineHandle) && ...
            lineHandle ~= -1

        delete_line( ...
            lineHandle);

    end

catch
end

end


% ============================================================
% GET ENTITY OUTPUT PORT
% ============================================================

function h = getEntityOutput( ...
    portHandles, ...
    index)

if isfield( ...
        portHandles, ...
        'RConn') && ...
        length(portHandles.RConn) >= index

    h = ...
        portHandles.RConn(index);

    return;

end

if isfield( ...
        portHandles, ...
        'Outport') && ...
        length(portHandles.Outport) >= index

    h = ...
        portHandles.Outport(index);

    return;

end

error( ...
    ['Unable to resolve entity output port ' ...
     num2str(index)]);

end


% ============================================================
% GET ENTITY INPUT PORT
% ============================================================

function h = getEntityInput( ...
    portHandles, ...
    index)

if isfield( ...
        portHandles, ...
        'LConn') && ...
        length(portHandles.LConn) >= index

    h = ...
        portHandles.LConn(index);

    return;

end

if isfield( ...
        portHandles, ...
        'Inport') && ...
        length(portHandles.Inport) >= index

    h = ...
        portHandles.Inport(index);

    return;

end

error( ...
    ['Unable to resolve entity input port ' ...
     num2str(index)]);

end


% ============================================================
% VERIFY ENTITY INPUT CONNECTED
% ============================================================

function verifyEntityInputConnected( ...
    blockPath)

portHandles = get_param( ...
    blockPath, ...
    'PortHandles');

inputPort = getEntityInput( ...
    portHandles, ...
    1);

lineHandle = get_param( ...
    inputPort, ...
    'Line');

if isempty(lineHandle) || ...
        lineHandle == -1

    error( ...
        ['Critical entity input disconnected: ' ...
         blockPath]);

end

fprintf( ...
    'CONNECTED: %s\n', ...
    blockPath);

end


% ============================================================
% GET LAST LOGGED VALUE
% ============================================================

function value = getLastMetric(data)

if isempty(data)

    value = 0;

elseif size(data,2) >= 2

    value = ...
        data(end,2);

else

    value = ...
        data(end);

end

end