function result = run_netraai_district_v4()
% RUN_NETRAAI_DISTRICT_V4
%
% ANEYE / NetraAI
% District-scale 100,000-screening/year stress scenario.
%
% BASE MODEL:
%   NetraAI_DigitalTwin_V3_1
%
% PURPOSE:
%   Test whether the current capture + AI + review resources
%   can sustain a 100,000-screenings/year operational target.
%
% IMPORTANT:
%   This is an ENGINEERING DIGITAL-TWIN SCENARIO.
%   It is NOT clinical deployment validation.
%
% PROVENANCE
% ------------------------------------------------------------
% REQUIREMENT:
%   Annual screening target = 100,000
%
% MEASURED:
%   AI processing = 8.67151 s
%   Source: one frozen reference case
%
% ASSUMPTION:
%   300 operating days/year
%   8 operating hours/day
%   Fundus capture = 120 s
%   Ophthalmology review = 30 s
%   Human review = 45 s
%
% ENGINEERING TEST:
%   TRACE route mix = balanced 20% per route
%
% SIMULATED:
%   queue waits
%   resource utilization
%   throughput
%   incomplete cases
%   annualized capacity
%   bottleneck

clc

fprintf('\n');
fprintf('====================================================\n');
fprintf(' ANEYE / NETRAAI DIGITAL TWIN V4\n');
fprintf(' DISTRICT 100,000 SCREENINGS/YEAR STRESS TEST\n');
fprintf('====================================================\n');

% ============================================================
% 1. PROJECT PATHS
% ============================================================

projectRoot = pwd;

modelDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'simulink');

resultsDir = fullfile( ...
    modelDir, ...
    'results');

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

baseModel = ...
    'NetraAI_DigitalTwin_V3_1';

mdl = ...
    'NetraAI_DigitalTwin_V4_District';

baseModelFile = fullfile( ...
    modelDir, ...
    [baseModel '.mdl']);

modelFile = fullfile( ...
    modelDir, ...
    [mdl '.mdl']);

% ------------------------------------------------------------
% Verify V3.1 baseline exists
% ------------------------------------------------------------

if exist(baseModelFile,'file') ~= 2

    error( ...
        ['V3.1 baseline model not found: ' ...
         baseModelFile]);

end

fprintf('\nBaseline model:\n%s\n',baseModelFile);

% ============================================================
% 2. SCENARIO PARAMETERS
% ============================================================

annualTarget = 100000;

workingDaysPerYear = 300;
operatingHoursPerDay = 8;

simulationHours = ...
    operatingHoursPerDay;

simulationTime = ...
    simulationHours * 3600;

% ------------------------------------------------------------
% Required operating rate
% ------------------------------------------------------------

operatingSecondsPerYear = ...
    workingDaysPerYear ...
    * operatingHoursPerDay ...
    * 3600;

arrivalPeriod = ...
    operatingSecondsPerYear ...
    / annualTarget;

targetCasesPerDay = ...
    annualTarget ...
    / workingDaysPerYear;

targetCasesPerHour = ...
    targetCasesPerDay ...
    / operatingHoursPerDay;

% ------------------------------------------------------------
% Service-time values
% ------------------------------------------------------------

captureTime = 120.0;
% ASSUMPTION

aiTime = 8.67151;
% MEASURED - SINGLE REFERENCE CASE

ophthalmologyTime = 30.0;
% ASSUMPTION

humanReviewTime = 45.0;
% ASSUMPTION

% ============================================================
% 3. PRINT SCENARIO CONTRACT
% ============================================================

fprintf('\n--- SCENARIO CONTRACT ---\n');

fprintf( ...
    'Annual target            : %.0f cases/year\n', ...
    annualTarget);

fprintf( ...
    'Operating days           : %.0f days/year [ASSUMPTION]\n', ...
    workingDaysPerYear);

fprintf( ...
    'Operating hours          : %.0f h/day [ASSUMPTION]\n', ...
    operatingHoursPerDay);

fprintf( ...
    'Required cases/day       : %.2f\n', ...
    targetCasesPerDay);

fprintf( ...
    'Required cases/hour      : %.2f\n', ...
    targetCasesPerHour);

fprintf( ...
    'Required arrival period  : %.3f s\n', ...
    arrivalPeriod);

fprintf( ...
    'Capture service          : %.2f s [ASSUMPTION]\n', ...
    captureTime);

fprintf( ...
    'AI service               : %.5f s [MEASURED-1 CASE]\n', ...
    aiTime);

fprintf( ...
    'Ophthalmology review     : %.2f s [ASSUMPTION]\n', ...
    ophthalmologyTime);

fprintf( ...
    'Human review             : %.2f s [ASSUMPTION]\n', ...
    humanReviewTime);

fprintf( ...
    'TRACE route mix          : 20%% each [ENGINEERING TEST]\n');

fprintf( ...
    'Simulation horizon       : %.0f h\n', ...
    simulationHours);

% ============================================================
% 4. CLEAN OLD V4 MODEL
% ============================================================

try
    close_system(mdl,0);
catch
end

if exist(modelFile,'file') == 2

    delete(modelFile);

end

% ============================================================
% 5. CLONE V3.1 BASELINE
% ============================================================

fprintf('\nLoading V3.1 baseline...\n');

load_system(baseModelFile);

fprintf('Baseline loaded.\n');

save_system( ...
    baseModel, ...
    modelFile);

try
    close_system(baseModel,0);
catch
end

load_system(modelFile);

fprintf('V4 district model cloned.\n');

% ============================================================
% 6. BLOCK PATHS
% ============================================================

arrival = ...
    [mdl '/Patient Arrival'];

captureQueue = ...
    [mdl '/Capture Queue'];

captureServer = ...
    [mdl '/Fundus Capture'];

aiQueue = ...
    [mdl '/AI Queue'];

aiServer = ...
    [mdl '/TRACE AI Processing'];

ophQueue = ...
    [mdl '/Ophthalmology Queue'];

ophServer = ...
    [mdl '/Ophthalmologist Review'];

humanQueue = ...
    [mdl '/Human Review Queue'];

humanServer = ...
    [mdl '/Human Reviewer'];

% ============================================================
% 7. CONFIGURE DISTRICT ARRIVAL RATE
% ============================================================

set_param( ...
    arrival, ...
    'GenerateEntitiesUpon', ...
    'Intergeneration time from dialog');

set_param( ...
    arrival, ...
    'Distribution', ...
    'Constant');

set_param( ...
    arrival, ...
    'Period', ...
    num2str(arrivalPeriod,15));

set_param( ...
    arrival, ...
    'GenerateEntityAtSimulationStart', ...
    'on');

set_param( ...
    arrival, ...
    'ResponseWhenBlocked', ...
    'Pause generation');

% ============================================================
% 8. CONFIGURE CAPTURE SERVICE
% ============================================================

set_param( ...
    captureServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    captureServer, ...
    'ServiceTime', ...
    num2str(captureTime,15));

% ============================================================
% 9. CONFIGURE AI SERVICE
% ============================================================

set_param( ...
    aiServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    aiServer, ...
    'ServiceTime', ...
    num2str(aiTime,15));

% ============================================================
% 10. CONFIGURE OPHTHALMOLOGY SERVICE
% ============================================================

set_param( ...
    ophServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    ophServer, ...
    'ServiceTime', ...
    num2str(ophthalmologyTime,15));

% ============================================================
% 11. CONFIGURE HUMAN REVIEW SERVICE
% ============================================================

set_param( ...
    humanServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    humanServer, ...
    'ServiceTime', ...
    num2str(humanReviewTime,15));

% ============================================================
% 12. INCREASE QUEUE CAPACITY
% ============================================================
%
% Avoid a small queue capacity hiding the actual backlog.

set_param( ...
    captureQueue, ...
    'Capacity', ...
    '1000');

set_param( ...
    aiQueue, ...
    'Capacity', ...
    '1000');

set_param( ...
    ophQueue, ...
    'Capacity', ...
    '1000');

set_param( ...
    humanQueue, ...
    'Capacity', ...
    '1000');

% ============================================================
% 13. SIMULATION CONFIGURATION
% ============================================================

set_param( ...
    mdl, ...
    'StopTime', ...
    num2str(simulationTime));

set_param( ...
    mdl, ...
    'Solver', ...
    'VariableStepDiscrete');

set_param( ...
    mdl, ...
    'MaxStep', ...
    '1');

% ============================================================
% 14. DESCRIPTION
% ============================================================

descriptionText = [ ...
    'ANEYE / NetraAI Digital Twin V4 District Scenario. ' ...
    'Target = 100000 screenings/year. ' ...
    'Operating calendar, capture service, ophthalmology review ' ...
    'and human-review times are explicit engineering assumptions. ' ...
    'AI service time 8.67151 seconds is measured from one frozen ' ...
    'reference case only. Balanced TRACE route mix is an ' ...
    'engineering stress-test distribution and does not represent ' ...
    'clinical prevalence.'];

try

    set_param( ...
        mdl, ...
        'Description', ...
        descriptionText);

catch
end

save_system( ...
    mdl, ...
    modelFile);

% ============================================================
% 15. CLEAR OLD LEGACY LOGGING VARIABLES
% ============================================================
%
% IMPORTANT FOR R2014a:
% To Workspace blocks will be executed in BASE workspace.

evalin( ...
    'base', ...
    ['clear ' ...
     'v3Route1 v3Route2 v3Route3 v3Route4 v3Route5 ' ...
     'v3CaptureWait v3AIWait v3OphWait v3HumanWait ' ...
     'v3CaptureUtil v3AIUtil v3OphUtil v3HumanUtil']);

% ============================================================
% 16. RUN SIMULATION IN BASE WORKSPACE
% ============================================================
%
% R2014a COMPATIBILITY FIX:
%
% Running sim(mdl) directly inside this function can cause
% legacy To Workspace blocks to store variables in an
% inaccessible function workspace.
%
% We therefore execute sim(...) in BASE workspace explicitly.

fprintf('\nRunning district-scale simulation...\n');

simCommand = [ ...
    'sim(''' ...
    mdl ...
    ''');'];

evalin( ...
    'base', ...
    simCommand);

fprintf('Simulation complete.\n');

% ============================================================
% 17. VERIFY ALL OUTPUT VARIABLES EXIST
% ============================================================

requiredVars = { ...
    'v3Route1', ...
    'v3Route2', ...
    'v3Route3', ...
    'v3Route4', ...
    'v3Route5', ...
    'v3CaptureWait', ...
    'v3AIWait', ...
    'v3OphWait', ...
    'v3HumanWait', ...
    'v3CaptureUtil', ...
    'v3AIUtil', ...
    'v3OphUtil', ...
    'v3HumanUtil'};

fprintf('\nChecking simulation outputs...\n');

for k = 1:length(requiredVars)

    existsFlag = evalin( ...
        'base', ...
        ['exist(''' ...
         requiredVars{k} ...
         ''',''var'')']);

    if existsFlag ~= 1

        error( ...
            ['Missing SimEvents output variable: ' ...
             requiredVars{k}]);

    end

end

fprintf('All SimEvents output variables: PASS\n');

% ============================================================
% 18. READ ROUTE COUNTS
% ============================================================

counts = zeros(1,5);

for k = 1:5

    varName = ...
        ['v3Route' num2str(k)];

    x = evalin( ...
        'base', ...
        varName);

    if isempty(x)

        counts(k) = 0;

    elseif size(x,2) >= 2

        counts(k) = ...
            x(end,2);

    else

        counts(k) = ...
            x(end);

    end

end

% ============================================================
% 19. READ QUEUE WAIT STATISTICS
% ============================================================

captureWaitData = ...
    evalin('base','v3CaptureWait');

aiWaitData = ...
    evalin('base','v3AIWait');

ophWaitData = ...
    evalin('base','v3OphWait');

humanWaitData = ...
    evalin('base','v3HumanWait');

captureWait = ...
    getLastMetric(captureWaitData);

aiWait = ...
    getLastMetric(aiWaitData);

ophWait = ...
    getLastMetric(ophWaitData);

humanWait = ...
    getLastMetric(humanWaitData);

% ============================================================
% 20. READ UTILIZATION STATISTICS
% ============================================================

captureUtilData = ...
    evalin('base','v3CaptureUtil');

aiUtilData = ...
    evalin('base','v3AIUtil');

ophUtilData = ...
    evalin('base','v3OphUtil');

humanUtilData = ...
    evalin('base','v3HumanUtil');

captureUtil = ...
    getLastMetric(captureUtilData);

aiUtil = ...
    getLastMetric(aiUtilData);

ophUtil = ...
    getLastMetric(ophUtilData);

humanUtil = ...
    getLastMetric(humanUtilData);

% ============================================================
% 21. DERIVED METRICS
% ============================================================

totalCompleted = ...
    sum(counts);

achievedCasesPerHour = ...
    totalCompleted ...
    / simulationHours;

annualizedCapacity = ...
    achievedCasesPerHour ...
    * operatingHoursPerDay ...
    * workingDaysPerYear;

% Generator begins at simulation t = 0.
expectedGenerated = ...
    floor( ...
        simulationTime ...
        / arrivalPeriod) ...
    + 1;

incompleteAtStop = ...
    max( ...
        0, ...
        expectedGenerated ...
        - totalCompleted);

annualTargetMet = ...
    annualizedCapacity ...
    >= annualTarget;

completionFraction = ...
    totalCompleted ...
    / expectedGenerated;

% ============================================================
% 22. BOTTLENECK DETECTION
% ============================================================

utilValues = [ ...
    captureUtil, ...
    aiUtil, ...
    ophUtil, ...
    humanUtil];

resourceNames = { ...
    'FUNDUS_CAPTURE', ...
    'TRACE_AI', ...
    'OPHTHALMOLOGIST', ...
    'HUMAN_REVIEWER'};

[maxUtil,maxIndex] = ...
    max(utilValues);

bottleneck = ...
    resourceNames{maxIndex};

% ============================================================
% 23. RESULT STRUCT
% ============================================================

result.scenario = ...
    'DISTRICT_100K_STRESS_V1';

result.provenance.annualTarget = ...
    'REQUIREMENT';

result.provenance.operatingCalendar = ...
    'ASSUMPTION';

result.provenance.captureTime = ...
    'ASSUMPTION';

result.provenance.aiTime = ...
    'MEASURED_SINGLE_REFERENCE_CASE';

result.provenance.reviewTimes = ...
    'ASSUMPTION';

result.provenance.routeMix = ...
    'ENGINEERING_TEST';

result.provenance.outputMetrics = ...
    'SIMULATED';

% ------------------------------------------------------------
% Target
% ------------------------------------------------------------

result.target.annualCases = ...
    annualTarget;

result.target.casesPerDay = ...
    targetCasesPerDay;

result.target.casesPerHour = ...
    targetCasesPerHour;

result.target.arrivalPeriodSec = ...
    arrivalPeriod;

% ------------------------------------------------------------
% Assumptions
% ------------------------------------------------------------

result.assumptions.workingDaysPerYear = ...
    workingDaysPerYear;

result.assumptions.operatingHoursPerDay = ...
    operatingHoursPerDay;

result.assumptions.captureTimeSec = ...
    captureTime;

result.assumptions.ophthalmologyTimeSec = ...
    ophthalmologyTime;

result.assumptions.humanReviewTimeSec = ...
    humanReviewTime;

% ------------------------------------------------------------
% Measured input
% ------------------------------------------------------------

result.measured.aiTimeSec = ...
    aiTime;

result.measured.aiTimingSource = ...
    'SINGLE_REFERENCE_CASE';

% ------------------------------------------------------------
% Routes
% ------------------------------------------------------------

result.routes = ...
    counts;

% ------------------------------------------------------------
% Queue waits
% ------------------------------------------------------------

result.wait.captureSec = ...
    captureWait;

result.wait.aiSec = ...
    aiWait;

result.wait.ophthalmologySec = ...
    ophWait;

result.wait.humanReviewSec = ...
    humanWait;

% ------------------------------------------------------------
% Utilization
% ------------------------------------------------------------

result.utilization.capture = ...
    captureUtil;

result.utilization.ai = ...
    aiUtil;

result.utilization.ophthalmology = ...
    ophUtil;

result.utilization.humanReview = ...
    humanUtil;

% ------------------------------------------------------------
% Throughput
% ------------------------------------------------------------

result.throughput.completed = ...
    totalCompleted;

result.throughput.expectedGenerated = ...
    expectedGenerated;

result.throughput.incompleteAtStop = ...
    incompleteAtStop;

result.throughput.completionFraction = ...
    completionFraction;

result.throughput.casesPerHour = ...
    achievedCasesPerHour;

result.throughput.annualizedCapacity = ...
    annualizedCapacity;

result.targetMet = ...
    annualTargetMet;

result.bottleneck = ...
    bottleneck;

result.bottleneckUtilization = ...
    maxUtil;

% ============================================================
% 24. PRINT RESULTS
% ============================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf(' NETRAAI V4 DISTRICT RESULTS\n');
fprintf('====================================================\n');

fprintf('\n--- TRACE ROUTES [SIMULATED] ---\n');

fprintf( ...
    'Routine             : %.0f\n', ...
    counts(1));

fprintf( ...
    'Ophthalmology       : %.0f\n', ...
    counts(2));

fprintf( ...
    'Human Review        : %.0f\n', ...
    counts(3));

fprintf( ...
    'Review / Recapture  : %.0f\n', ...
    counts(4));

fprintf( ...
    'Recapture           : %.0f\n', ...
    counts(5));

fprintf('\n--- QUEUE WAIT [SIMULATED] ---\n');

fprintf( ...
    'Capture             : %.3f s\n', ...
    captureWait);

fprintf( ...
    'AI                  : %.3f s\n', ...
    aiWait);

fprintf( ...
    'Ophthalmology       : %.3f s\n', ...
    ophWait);

fprintf( ...
    'Human Review        : %.3f s\n', ...
    humanWait);

fprintf('\n--- UTILIZATION [SIMULATED] ---\n');

fprintf( ...
    'Fundus Capture      : %.4f\n', ...
    captureUtil);

fprintf( ...
    'TRACE AI            : %.4f\n', ...
    aiUtil);

fprintf( ...
    'Ophthalmologist     : %.4f\n', ...
    ophUtil);

fprintf( ...
    'Human Reviewer      : %.4f\n', ...
    humanUtil);

fprintf('\n--- CAPACITY ---\n');

fprintf( ...
    'Generated cases     : %.0f\n', ...
    expectedGenerated);

fprintf( ...
    'Completed cases     : %.0f\n', ...
    totalCompleted);

fprintf( ...
    'Incomplete at stop  : %.0f\n', ...
    incompleteAtStop);

fprintf( ...
    'Completion fraction : %.4f\n', ...
    completionFraction);

fprintf( ...
    'Achieved cases/hour : %.2f\n', ...
    achievedCasesPerHour);

fprintf( ...
    'Annualized capacity : %.0f cases/year\n', ...
    annualizedCapacity);

fprintf( ...
    'Required target     : %.0f cases/year\n', ...
    annualTarget);

fprintf('\n--- BOTTLENECK ---\n');

fprintf( ...
    'Highest utilization : %s\n', ...
    bottleneck);

fprintf( ...
    'Utilization         : %.4f\n', ...
    maxUtil);

fprintf('\n');

if annualTargetMet

    fprintf('TARGET STATUS: PASS\n');

else

    fprintf('TARGET STATUS: CAPACITY GAP\n');

end

fprintf('====================================================\n');

% ============================================================
% 25. SAVE RESULT MAT FILE
% ============================================================

resultMat = fullfile( ...
    resultsDir, ...
    'NetraAI_V4_District_100K_Result.mat');

save( ...
    resultMat, ...
    'result');

% ============================================================
% 26. SAVE TEXT REPORT
% ============================================================

reportFile = fullfile( ...
    resultsDir, ...
    'NetraAI_V4_District_100K_Report.txt');

fid = fopen( ...
    reportFile, ...
    'w');

if fid ~= -1

    fprintf(fid, ...
        'ANEYE / NetraAI Digital Twin V4\n');

    fprintf(fid, ...
        'District 100,000 Screenings/Year Stress Test\n\n');

    fprintf(fid, ...
        'PROVENANCE\n');

    fprintf(fid, ...
        'Annual target: REQUIREMENT\n');

    fprintf(fid, ...
        'Operating calendar: ASSUMPTION\n');

    fprintf(fid, ...
        'Capture time: ASSUMPTION\n');

    fprintf(fid, ...
        'AI time: MEASURED_SINGLE_REFERENCE_CASE\n');

    fprintf(fid, ...
        'Review times: ASSUMPTION\n');

    fprintf(fid, ...
        'TRACE route mix: ENGINEERING_TEST\n');

    fprintf(fid, ...
        'Output metrics: SIMULATED\n\n');

    fprintf(fid, ...
        'TARGET\n');

    fprintf(fid, ...
        'Annual target: %.0f\n', ...
        annualTarget);

    fprintf(fid, ...
        'Required cases/day: %.4f\n', ...
        targetCasesPerDay);

    fprintf(fid, ...
        'Required cases/hour: %.4f\n', ...
        targetCasesPerHour);

    fprintf(fid, ...
        'Arrival period: %.4f s\n', ...
        arrivalPeriod);

    fprintf(fid, ...
        '\nSERVICE VALUES\n');

    fprintf(fid, ...
        'Capture service: %.4f s [ASSUMPTION]\n', ...
        captureTime);

    fprintf(fid, ...
        'AI service: %.5f s [MEASURED-1 CASE]\n', ...
        aiTime);

    fprintf(fid, ...
        'Ophthalmology review: %.4f s [ASSUMPTION]\n', ...
        ophthalmologyTime);

    fprintf(fid, ...
        'Human review: %.4f s [ASSUMPTION]\n', ...
        humanReviewTime);

    fprintf(fid, ...
        '\nTRACE ROUTES\n');

    for k = 1:5

        fprintf(fid, ...
            'Route %d: %.0f\n', ...
            k, ...
            counts(k));

    end

    fprintf(fid, ...
        '\nQUEUE WAIT\n');

    fprintf(fid, ...
        'Capture: %.4f s\n', ...
        captureWait);

    fprintf(fid, ...
        'AI: %.4f s\n', ...
        aiWait);

    fprintf(fid, ...
        'Ophthalmology: %.4f s\n', ...
        ophWait);

    fprintf(fid, ...
        'Human Review: %.4f s\n', ...
        humanWait);

    fprintf(fid, ...
        '\nUTILIZATION\n');

    fprintf(fid, ...
        'Capture: %.6f\n', ...
        captureUtil);

    fprintf(fid, ...
        'AI: %.6f\n', ...
        aiUtil);

    fprintf(fid, ...
        'Ophthalmologist: %.6f\n', ...
        ophUtil);

    fprintf(fid, ...
        'Human Reviewer: %.6f\n', ...
        humanUtil);

    fprintf(fid, ...
        '\nCAPACITY\n');

    fprintf(fid, ...
        'Generated: %.0f\n', ...
        expectedGenerated);

    fprintf(fid, ...
        'Completed: %.0f\n', ...
        totalCompleted);

    fprintf(fid, ...
        'Incomplete at stop: %.0f\n', ...
        incompleteAtStop);

    fprintf(fid, ...
        'Completion fraction: %.6f\n', ...
        completionFraction);

    fprintf(fid, ...
        'Cases/hour: %.4f\n', ...
        achievedCasesPerHour);

    fprintf(fid, ...
        'Annualized capacity: %.0f\n', ...
        annualizedCapacity);

    fprintf(fid, ...
        '\nBOTTLENECK\n');

    fprintf(fid, ...
        'Resource: %s\n', ...
        bottleneck);

    fprintf(fid, ...
        'Utilization: %.6f\n', ...
        maxUtil);

    if annualTargetMet

        fprintf(fid, ...
            '\nTarget status: PASS\n');

    else

        fprintf(fid, ...
            '\nTarget status: CAPACITY GAP\n');

    end

    fclose(fid);

end

% ============================================================
% 27. FINAL SAVE
% ============================================================

save_system( ...
    mdl, ...
    modelFile);

fprintf('\nSaved MAT result:\n%s\n',resultMat);

fprintf('\nSaved text report:\n%s\n',reportFile);

fprintf('\nV4 model:\n%s\n',modelFile);

open_system(mdl);

end


% ============================================================
% HELPER: GET LAST VALUE FROM R2014a TO WORKSPACE ARRAY
% ============================================================

function value = getLastMetric(data)

if isempty(data)

    value = 0;

elseif size(data,2) >= 2

    value = data(end,2);

else

    value = data(end);

end

end