function result = run_netraai_recapture_v6()
% RUN_NETRAAI_RECAPTURE_V6
%
% ANEYE / NetraAI Digital Twin V6
% ONE-PASS RECAPTURE RESOURCE LOOP
%
% MATLAB / SimEvents R2014a compatible.
%
% BASE MODEL
% ----------
% NetraAI_DigitalTwin_V5_ParallelCapture
%
% KEY V6 CHANGE
% -------------
% Primary and recapture traffic are merged using:
%
%       simeventslib/Routing/Path Combiner
%
% NOT Input Switch.
%
% This avoids the R2014a Round-Robin Input Switch deadlock where
% the switch can wait for an empty feedback input.
%
%
% PRIMARY FLOW
% ------------
%
% Population Merger
%        |
% Set flowType = 1
%        |
%        +-----------------------------+
%                                      |
%                               Path Combiner
%                                      |
%                            Capture Load Balancer
%                               /             \
%                        Capture 1         Capture 2
%                               \             /
%                                Capture Merger
%                                      |
%                                  AI Queue
%                                      |
%                                   TRACE AI
%                                      |
%                              Post-AI Flow Router
%                               /              \
%                     flowType=1              flowType=2
%                         |                       |
%                    TRACE Router          RECAPTURE COMPLETE
%
%
% RECAPTURE FLOW
% --------------
%
% TRACE Route 5
%       |
% Recapture Preparation
%       |
% Set flowType = 2
%       |
% Path Combiner
%       |
% second Capture
%       |
% second AI pass
%       |
% RECAPTURE COMPLETE
%
%
% IMPORTANT
% ---------
% A recapture is allowed ONE additional acquisition/AI pass.
% It does NOT enter TRACE routing for a second time.
%
% Therefore routeCode=5 cannot create an infinite loop.
%
% Post-recapture clinical outcome is NOT inferred because that
% behavior has not yet been measured.
%
%
% PROVENANCE
% ----------
% REQUIREMENT
%   Annual target = 100,000 primary screenings
%
% MEASURED
%   AI service time = 8.67151 s
%   based on one frozen reference case only
%
% ASSUMPTION
%   300 operating days/year
%   8 operating hours/day
%   Capture service = 120 s
%   Recapture preparation = 20 s
%   Ophthalmology review = 30 s
%   Human review = 45 s
%
% ENGINEERING TEST
%   TRACE route mix = 20% each
%
% SIMULATED
%   Queue waits
%   Resource utilization
%   Recapture workload
%   Throughput
%
% This is an engineering digital twin.
% It is NOT clinical validation.

clc

fprintf('\n');
fprintf('========================================================\n');
fprintf(' ANEYE / NETRAAI DIGITAL TWIN V6\n');
fprintf(' PATH-COMBINER ONE-PASS RECAPTURE LOOP\n');
fprintf('========================================================\n');

% ============================================================
% 1. PATHS
% ============================================================

projectRoot = pwd;

srcDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'matlab', ...
    'src');

modelDir = fullfile( ...
    projectRoot, ...
    'nationals', ...
    'simulink');

resultsDir = fullfile( ...
    modelDir, ...
    'results');

addpath(srcDir);

if ~exist(resultsDir,'dir')
    mkdir(resultsDir);
end

baseModel = ...
    'NetraAI_DigitalTwin_V5_ParallelCapture';

mdl = ...
    'NetraAI_DigitalTwin_V6_RecaptureLoop';

baseModelFile = fullfile( ...
    modelDir, ...
    [baseModel '.mdl']);

modelFile = fullfile( ...
    modelDir, ...
    [mdl '.mdl']);

if exist(baseModelFile,'file') ~= 2

    error( ...
        ['V5 baseline model not found: ' ...
         baseModelFile]);

end

fprintf('\nValidated V5 baseline:\n%s\n', ...
    baseModelFile);

% ============================================================
% 2. DISTRICT SCENARIO
% ============================================================

annualTarget = 100000;

workingDays = 300;
hoursPerDay = 8;

simulationHours = 8;

simulationTime = ...
    simulationHours * 3600;

operatingSecondsYear = ...
    workingDays ...
    * hoursPerDay ...
    * 3600;

arrivalPeriod = ...
    operatingSecondsYear ...
    / annualTarget;

requiredPerHour = ...
    annualTarget ...
    / (workingDays * hoursPerDay);

captureTime = 120.0;
% ASSUMPTION

aiTime = 8.67151;
% MEASURED ON ONE REFERENCE CASE

ophthalmologyTime = 30.0;
% ASSUMPTION

humanReviewTime = 45.0;
% ASSUMPTION

recapturePreparationTime = 20.0;
% ASSUMPTION

% ============================================================
% 3. PRINT CONTRACT
% ============================================================

fprintf('\n--- V6 SCENARIO CONTRACT ---\n');

fprintf( ...
    'Annual requirement        : %.0f/year\n', ...
    annualTarget);

fprintf( ...
    'Required primary rate     : %.2f cases/hour\n', ...
    requiredPerHour);

fprintf( ...
    'Primary arrival period    : %.3f s\n', ...
    arrivalPeriod);

fprintf( ...
    'Capture stations          : 2\n');

fprintf( ...
    'Capture service           : %.2f s [ASSUMPTION]\n', ...
    captureTime);

fprintf( ...
    'AI service                : %.5f s [MEASURED-1 CASE]\n', ...
    aiTime);

fprintf( ...
    'Recapture preparation     : %.2f s [ASSUMPTION]\n', ...
    recapturePreparationTime);

fprintf( ...
    'TRACE route mix           : 20%% each [ENGINEERING TEST]\n');

fprintf( ...
    'Feedback merge            : PATH COMBINER\n');

fprintf( ...
    'Recapture policy          : ONE PASS ONLY\n');

fprintf( ...
    'Simulation horizon        : %.0f h\n', ...
    simulationHours);

% ============================================================
% 4. REMOVE OLD V6
% ============================================================

try
    close_system(mdl,0);
catch
end

if exist(modelFile,'file') == 2
    delete(modelFile);
end

% ============================================================
% 5. CLONE VALIDATED V5
% ============================================================

fprintf('\nLoading V5 baseline...\n');

load_system(baseModelFile);

save_system( ...
    baseModel, ...
    modelFile);

try
    close_system(baseModel,0);
catch
end

load_system(modelFile);

fprintf('Fresh V6 cloned from validated V5.\n');

% ============================================================
% 6. LOAD LIBRARIES
% ============================================================

load_system('simeventslib');

pathCombinerLib = ...
    'simeventslib/Routing/Path Combiner';

outputSwitchLib = ...
    'simeventslib/Routing/Output Switch';

serverLib = ...
    'simeventslib/Servers/Single Server';

setAttributeLib = ...
    'simeventslib/Attributes/Set Attribute';

sinkLib = findLegacyBlock( ...
    'simeventslib', ...
    'Entity Sink');

% ============================================================
% 7. V5 BLOCK PATHS
% ============================================================

populationMerger = ...
    [mdl '/Population Merger'];

captureLoadBalancer = ...
    [mdl '/Capture Load Balancer'];

captureQueue1 = ...
    [mdl '/Capture Queue'];

captureQueue2 = ...
    [mdl '/Capture Queue 2'];

captureServer1 = ...
    [mdl '/Fundus Capture'];

captureServer2 = ...
    [mdl '/Fundus Capture 2'];

captureMerger = ...
    [mdl '/Capture Merger'];

aiQueue = ...
    [mdl '/AI Queue'];

aiServer = ...
    [mdl '/TRACE AI Processing'];

traceRouter = ...
    [mdl '/TRACE Router'];

ophServer = ...
    [mdl '/Ophthalmologist Review'];

humanServer = ...
    [mdl '/Human Reviewer'];

oldRecaptureSink = ...
    [mdl '/5 RECAPTURE'];

oldRoute5Logger = ...
    [mdl '/Route 5 Count'];

% ============================================================
% 8. VERIFY V5 STRUCTURE
% ============================================================

requiredBlocks = { ...
    populationMerger, ...
    captureLoadBalancer, ...
    captureQueue1, ...
    captureQueue2, ...
    captureServer1, ...
    captureServer2, ...
    captureMerger, ...
    aiQueue, ...
    aiServer, ...
    traceRouter};

for k = 1:length(requiredBlocks)

    try

        get_param( ...
            requiredBlocks{k}, ...
            'Handle');

    catch

        error( ...
            ['Required V5 block missing: ' ...
             requiredBlocks{k}]);

    end

end

fprintf('V5 structural verification: PASS\n');

% ============================================================
% 9. REMOVE OLD TERMINAL RECAPTURE PATH
% ============================================================

fprintf('\nRemoving V5 terminal recapture path...\n');

try
    delete_block(oldRoute5Logger);
catch
end

try
    delete_block(oldRecaptureSink);
catch
end

fprintf('V5 Route-5 sink removed.\n');

% ============================================================
% 10. CREATE PRIMARY FLOW ATTRIBUTE
% ============================================================
%
% flowType = 1 : primary
% flowType = 2 : recapture

primaryFlowSetter = ...
    [mdl '/Set Primary Flow'];

try
    delete_block(primaryFlowSetter);
catch
end

add_block( ...
    setAttributeLib, ...
    primaryFlowSetter, ...
    'Position', ...
    [555 385 700 435]);

set_param( ...
    primaryFlowSetter, ...
    'AttributeName', ...
    'flowType');

set_param( ...
    primaryFlowSetter, ...
    'AttributeFrom', ...
    'Dialog');

set_param( ...
    primaryFlowSetter, ...
    'AttributeValue', ...
    '1');

set_param( ...
    primaryFlowSetter, ...
    'AttributeCreate', ...
    'on');

% ============================================================
% 11. CREATE PATH COMBINER
% ============================================================
%
% This is the critical R2014a fix.
%
% IN1 = primary cases
% IN2 = recapture feedback
%
% Unlike Input Switch, Path Combiner does not need to select
% an empty input before allowing the other input to pass.

acquisitionCombiner = ...
    [mdl '/Acquisition Path Combiner'];

try
    delete_block(acquisitionCombiner);
catch
end

add_block( ...
    pathCombinerLib, ...
    acquisitionCombiner, ...
    'Position', ...
    [750 370 890 475]);

set_param( ...
    acquisitionCombiner, ...
    'NumberInputPorts', ...
    '2');

% Prefer new primary input only when arrivals occur at the
% exact same simulation event time.
%
% This does NOT create the Round-Robin deadlock.

set_param( ...
    acquisitionCombiner, ...
    'InputPortPrecedence', ...
    'IN1 port');

set_param( ...
    acquisitionCombiner, ...
    'SpecifyEventPriority', ...
    'off');

fprintf('Acquisition Path Combiner created.\n');

% ============================================================
% 12. CREATE PRIMARY ENTRY PATH
% ============================================================

forceEntityConnection( ...
    mdl, ...
    populationMerger, ...
    primaryFlowSetter);

forceEntityToInputConnection( ...
    mdl, ...
    primaryFlowSetter, ...
    acquisitionCombiner, ...
    1);

forceEntityConnection( ...
    mdl, ...
    acquisitionCombiner, ...
    captureLoadBalancer);

fprintf('Primary -> Path Combiner path connected.\n');

% ============================================================
% 13. CREATE POST-AI FLOW ROUTER
% ============================================================

postAIRouter = ...
    [mdl '/Post AI Flow Router'];

try
    delete_block(postAIRouter);
catch
end

add_block( ...
    outputSwitchLib, ...
    postAIRouter, ...
    'Position', ...
    [1765 180 1900 310]);

set_param( ...
    postAIRouter, ...
    'NumberOutputPorts', ...
    '2');

set_param( ...
    postAIRouter, ...
    'SwitchingCriterion', ...
    'From attribute');

set_param( ...
    postAIRouter, ...
    'AttributeName', ...
    'flowType');

% ============================================================
% 14. RECAPTURE COMPLETE SINK
% ============================================================

recaptureCompleteSink = ...
    [mdl '/RECAPTURE COMPLETE'];

try
    delete_block(recaptureCompleteSink);
catch
end

add_block( ...
    sinkLib, ...
    recaptureCompleteSink, ...
    'Position', ...
    [2020 315 2180 370]);

set_param( ...
    recaptureCompleteSink, ...
    'StatNumberArrived', ...
    'on');

% ============================================================
% 15. RECAPTURE PREPARATION SERVER
% ============================================================

recaptureDelay = ...
    [mdl '/Recapture Preparation'];

try
    delete_block(recaptureDelay);
catch
end

add_block( ...
    serverLib, ...
    recaptureDelay, ...
    'Position', ...
    [1510 600 1665 650]);

set_param( ...
    recaptureDelay, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    recaptureDelay, ...
    'ServiceTime', ...
    num2str(recapturePreparationTime,15));

% ============================================================
% 16. RECAPTURE FLOW ATTRIBUTE
% ============================================================

recaptureFlowSetter = ...
    [mdl '/Set Recapture Flow'];

try
    delete_block(recaptureFlowSetter);
catch
end

add_block( ...
    setAttributeLib, ...
    recaptureFlowSetter, ...
    'Position', ...
    [1710 600 1860 650]);

set_param( ...
    recaptureFlowSetter, ...
    'AttributeName', ...
    'flowType');

set_param( ...
    recaptureFlowSetter, ...
    'AttributeFrom', ...
    'Dialog');

set_param( ...
    recaptureFlowSetter, ...
    'AttributeValue', ...
    '2');

set_param( ...
    recaptureFlowSetter, ...
    'AttributeCreate', ...
    'on');

% ============================================================
% 17. REBUILD FULL CAPTURE PIPELINE
% ============================================================

fprintf('\nRebuilding capture pipeline...\n');

% Path Combiner -> capture load balancer

forceEntityConnection( ...
    mdl, ...
    acquisitionCombiner, ...
    captureLoadBalancer);

% Capture load balancer -> queue 1

forceEntityOutputConnection( ...
    mdl, ...
    captureLoadBalancer, ...
    captureQueue1, ...
    1);

% Capture load balancer -> queue 2

forceEntityOutputConnection( ...
    mdl, ...
    captureLoadBalancer, ...
    captureQueue2, ...
    2);

% Queue 1 -> Camera 1

forceEntityConnection( ...
    mdl, ...
    captureQueue1, ...
    captureServer1);

% Queue 2 -> Camera 2

forceEntityConnection( ...
    mdl, ...
    captureQueue2, ...
    captureServer2);

% Camera 1 -> Capture Merger IN1

forceEntityToInputConnection( ...
    mdl, ...
    captureServer1, ...
    captureMerger, ...
    1);

% Camera 2 -> Capture Merger IN2

forceEntityToInputConnection( ...
    mdl, ...
    captureServer2, ...
    captureMerger, ...
    2);

% Capture Merger -> AI queue

forceEntityConnection( ...
    mdl, ...
    captureMerger, ...
    aiQueue);

% AI queue -> TRACE AI

forceEntityConnection( ...
    mdl, ...
    aiQueue, ...
    aiServer);

% TRACE AI -> post-AI flow router

forceEntityConnection( ...
    mdl, ...
    aiServer, ...
    postAIRouter);

% flowType 1 -> TRACE Router

forceEntityOutputConnection( ...
    mdl, ...
    postAIRouter, ...
    traceRouter, ...
    1);

% flowType 2 -> recapture complete

forceEntityOutputConnection( ...
    mdl, ...
    postAIRouter, ...
    recaptureCompleteSink, ...
    2);

fprintf('Capture + AI pipeline rebuilt.\n');

% ============================================================
% 18. CREATE RECAPTURE FEEDBACK PATH
% ============================================================

fprintf('Building Route-5 feedback path...\n');

% TRACE Route 5 -> recapture preparation

forceEntityOutputConnection( ...
    mdl, ...
    traceRouter, ...
    recaptureDelay, ...
    5);

% preparation -> flowType=2

forceEntityConnection( ...
    mdl, ...
    recaptureDelay, ...
    recaptureFlowSetter);

% flowType=2 -> Path Combiner IN2

forceEntityToInputConnection( ...
    mdl, ...
    recaptureFlowSetter, ...
    acquisitionCombiner, ...
    2);

fprintf('Route-5 Path Combiner feedback connected.\n');

% ============================================================
% 19. SERVICE TIMES
% ============================================================

set_param( ...
    captureServer1, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    captureServer1, ...
    'ServiceTime', ...
    num2str(captureTime,15));

set_param( ...
    captureServer2, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    captureServer2, ...
    'ServiceTime', ...
    num2str(captureTime,15));

set_param( ...
    aiServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    aiServer, ...
    'ServiceTime', ...
    num2str(aiTime,15));

set_param( ...
    ophServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    ophServer, ...
    'ServiceTime', ...
    num2str(ophthalmologyTime,15));

set_param( ...
    humanServer, ...
    'ServiceTimeFrom', ...
    'Dialog');

set_param( ...
    humanServer, ...
    'ServiceTime', ...
    num2str(humanReviewTime,15));

% ============================================================
% 20. ROUTE LOGGERS
% ============================================================

setLoggerVariable( ...
    mdl, ...
    'Route 1 Count', ...
    'v6Route1');

setLoggerVariable( ...
    mdl, ...
    'Route 2 Count', ...
    'v6Route2');

setLoggerVariable( ...
    mdl, ...
    'Route 3 Count', ...
    'v6Route3');

setLoggerVariable( ...
    mdl, ...
    'Route 4 Count', ...
    'v6Route4');

% ============================================================
% 21. QUEUE LOGGERS
% ============================================================

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 1', ...
    'v6Capture1Wait');

setLoggerVariable( ...
    mdl, ...
    'Metric Capture2 Wait', ...
    'v6Capture2Wait');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 2', ...
    'v6AIWait');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 3', ...
    'v6OphWait');

setLoggerVariable( ...
    mdl, ...
    'Metric Queue 4', ...
    'v6HumanWait');

% ============================================================
% 22. UTILIZATION LOGGERS
% ============================================================

setLoggerVariable( ...
    mdl, ...
    'Metric Util 1', ...
    'v6Capture1Util');

setLoggerVariable( ...
    mdl, ...
    'Metric Capture2 Util', ...
    'v6Capture2Util');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 2', ...
    'v6AIUtil');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 3', ...
    'v6OphUtil');

setLoggerVariable( ...
    mdl, ...
    'Metric Util 4', ...
    'v6HumanUtil');

% ============================================================
% 23. RECAPTURE SERVER STATISTICS
% ============================================================

set_param( ...
    recaptureDelay, ...
    'StatUtilization', ...
    'on');

set_param( ...
    recaptureDelay, ...
    'StatNumberDeparted', ...
    'off');

set_param( ...
    recaptureDelay, ...
    'StatNumberInBlock', ...
    'off');

set_param( ...
    recaptureDelay, ...
    'StatNumberPreempted', ...
    'off');

set_param( ...
    recaptureDelay, ...
    'StatPendingEntity', ...
    'off');

set_param( ...
    recaptureDelay, ...
    'StatAverageWait', ...
    'off');

set_param( ...
    recaptureDelay, ...
    'StatNumberTimedout', ...
    'off');

% ============================================================
% 24. UPDATE MODEL / GENERATE STAT PORTS
% ============================================================

set_param( ...
    mdl, ...
    'SimulationCommand', ...
    'update');

% ============================================================
% 25. RECAPTURE COMPLETE LOGGER
% ============================================================

recaptureCompleteLogger = ...
    [mdl '/Recapture Complete Count'];

try
    delete_block(recaptureCompleteLogger);
catch
end

add_block( ...
    'simulink/Sinks/To Workspace', ...
    recaptureCompleteLogger, ...
    'VariableName', ...
    'v6RecaptureComplete', ...
    'SaveFormat', ...
    'Array', ...
    'Position', ...
    [2210 315 2370 350]);

sinkPorts = get_param( ...
    recaptureCompleteSink, ...
    'PortHandles');

loggerPorts = get_param( ...
    recaptureCompleteLogger, ...
    'PortHandles');

if isempty(sinkPorts.Outport)

    error( ...
        'RECAPTURE COMPLETE statistic port unavailable.');

end

add_line( ...
    mdl, ...
    sinkPorts.Outport(1), ...
    loggerPorts.Inport(1), ...
    'autorouting', ...
    'on');

% ============================================================
% 26. RECAPTURE PREP UTILIZATION LOGGER
% ============================================================

recaptureUtilLogger = ...
    [mdl '/Metric Recapture Prep Util'];

try
    delete_block(recaptureUtilLogger);
catch
end

add_block( ...
    'simulink/Sinks/To Workspace', ...
    recaptureUtilLogger, ...
    'VariableName', ...
    'v6RecapturePrepUtil', ...
    'SaveFormat', ...
    'Array', ...
    'Position', ...
    [1700 690 1870 725]);

delayPorts = get_param( ...
    recaptureDelay, ...
    'PortHandles');

utilPorts = get_param( ...
    recaptureUtilLogger, ...
    'PortHandles');

if isempty(delayPorts.Outport)

    error( ...
        'Recapture Preparation utilization port unavailable.');

end

add_line( ...
    mdl, ...
    delayPorts.Outport(1), ...
    utilPorts.Inport(1), ...
    'autorouting', ...
    'on');

% ============================================================
% 27. VALIDATE PATH COMBINER
% ============================================================

fprintf('\n--- PATH COMBINER VALIDATION ---\n');

combinerType = get_param( ...
    acquisitionCombiner, ...
    'BlockType');

combinerInputs = get_param( ...
    acquisitionCombiner, ...
    'NumberInputPorts');

combinerPrecedence = get_param( ...
    acquisitionCombiner, ...
    'InputPortPrecedence');

fprintf( ...
    'BlockType             : %s\n', ...
    combinerType);

fprintf( ...
    'NumberInputPorts      : %s\n', ...
    combinerInputs);

fprintf( ...
    'InputPortPrecedence   : %s\n', ...
    combinerPrecedence);

if ~strcmp( ...
        combinerType, ...
        'PathCombiner')

    error( ...
        'Acquisition merge is not a Path Combiner.');

end

if ~strcmp( ...
        combinerInputs, ...
        '2')

    error( ...
        'Acquisition Path Combiner does not have 2 inputs.');

end

fprintf('Path Combiner configuration: PASS\n');

% ============================================================
% 28. VALIDATE CRITICAL CONNECTIONS
% ============================================================

fprintf('\n--- CRITICAL CONNECTION VALIDATION ---\n');

verifyEntityInputConnected( ...
    primaryFlowSetter);

verifyEntityInputConnected( ...
    acquisitionCombiner);

verifyEntityInputConnected( ...
    captureLoadBalancer);

verifyEntityInputConnected( ...
    captureQueue1);

verifyEntityInputConnected( ...
    captureQueue2);

verifyEntityInputConnected( ...
    captureServer1);

verifyEntityInputConnected( ...
    captureServer2);

verifyEntityInputConnected( ...
    captureMerger);

verifyEntityInputConnected( ...
    aiQueue);

verifyEntityInputConnected( ...
    aiServer);

verifyEntityInputConnected( ...
    postAIRouter);

verifyEntityInputConnected( ...
    traceRouter);

verifyEntityInputConnected( ...
    recaptureDelay);

verifyEntityInputConnected( ...
    recaptureFlowSetter);

verifyEntityInputConnected( ...
    recaptureCompleteSink);

fprintf('Critical V6 connections: PASS\n');

% ============================================================
% 29. ROUTER INTEGRITY
% ============================================================

if ~strcmp( ...
        get_param( ...
            postAIRouter, ...
            'SwitchingCriterion'), ...
        'From attribute')

    error( ...
        'Post-AI Flow Router criterion invalid.');

end

if ~strcmp( ...
        get_param( ...
            postAIRouter, ...
            'AttributeName'), ...
        'flowType')

    error( ...
        'Post-AI Flow Router must use flowType.');

end

if ~strcmp( ...
        get_param( ...
            traceRouter, ...
            'SwitchingCriterion'), ...
        'From attribute')

    error( ...
        'TRACE Router criterion was changed.');

end

if ~strcmp( ...
        get_param( ...
            traceRouter, ...
            'AttributeName'), ...
        'routeCode')

    error( ...
        'TRACE Router must continue using routeCode.');

end

fprintf('Router integrity: PASS\n');

% ============================================================
% 30. SOLVER
% ============================================================

set_param( ...
    mdl, ...
    'StopTime', ...
    num2str(simulationTime));

set_param( ...
    mdl, ...
    'Solver', ...
    'VariableStepDiscrete');

set_param( ...
    mdl, ...
    'MaxStep', ...
    '1');

% ============================================================
% 31. MODEL DESCRIPTION
% ============================================================

descriptionText = [ ...
    'ANEYE / NetraAI Digital Twin V6. ' ...
    'Primary and recapture acquisition traffic are merged ' ...
    'using a SimEvents Path Combiner. Route-5 cases consume ' ...
    'recapture preparation, a second fundus capture and a ' ...
    'second AI pass. Recapture cases exit after the second ' ...
    'AI pass; post-recapture clinical outcome is not inferred.'];

try

    set_param( ...
        mdl, ...
        'Description', ...
        descriptionText);

catch
end

save_system( ...
    mdl, ...
    modelFile);

fprintf('\nV6 construction: PASS\n');

% ============================================================
% 32. CLEAR LOGGING VARIABLES
% ============================================================

evalin( ...
    'base', ...
    ['clear ' ...
     'v6Route1 v6Route2 v6Route3 v6Route4 ' ...
     'v6RecaptureComplete ' ...
     'v6Capture1Wait v6Capture2Wait ' ...
     'v6AIWait v6OphWait v6HumanWait ' ...
     'v6Capture1Util v6Capture2Util ' ...
     'v6AIUtil v6OphUtil v6HumanUtil ' ...
     'v6RecapturePrepUtil']);

% ============================================================
% 33. RUN SIMULATION
% ============================================================

fprintf('\nRunning corrected V6 simulation...\n');

simCommand = ...
    ['sim(''' mdl ''');'];

evalin( ...
    'base', ...
    simCommand);

fprintf('Simulation complete.\n');

% ============================================================
% 34. VERIFY OUTPUTS
% ============================================================

requiredVars = { ...
    'v6Route1', ...
    'v6Route2', ...
    'v6Route3', ...
    'v6Route4', ...
    'v6RecaptureComplete', ...
    'v6Capture1Wait', ...
    'v6Capture2Wait', ...
    'v6AIWait', ...
    'v6OphWait', ...
    'v6HumanWait', ...
    'v6Capture1Util', ...
    'v6Capture2Util', ...
    'v6AIUtil', ...
    'v6OphUtil', ...
    'v6HumanUtil', ...
    'v6RecapturePrepUtil'};

fprintf('\nChecking V6 logged outputs...\n');

for k = 1:length(requiredVars)

    existsFlag = evalin( ...
        'base', ...
        ['exist(''' ...
         requiredVars{k} ...
         ''',''var'')']);

    if existsFlag ~= 1

        error( ...
            ['Missing V6 output variable: ' ...
             requiredVars{k}]);

    end

end

fprintf('All V6 outputs: PASS\n');

% ============================================================
% 35. READ ROUTE COUNTS
% ============================================================

routeCounts = zeros(1,4);

for k = 1:4

    x = evalin( ...
        'base', ...
        ['v6Route' num2str(k)]);

    routeCounts(k) = ...
        getLastMetric(x);

end

recaptureComplete = ...
    getLastMetric( ...
        evalin( ...
            'base', ...
            'v6RecaptureComplete'));

% ============================================================
% 36. READ WAITS
% ============================================================

capture1Wait = ...
    getLastMetric( ...
        evalin('base','v6Capture1Wait'));

capture2Wait = ...
    getLastMetric( ...
        evalin('base','v6Capture2Wait'));

aiWait = ...
    getLastMetric( ...
        evalin('base','v6AIWait'));

ophWait = ...
    getLastMetric( ...
        evalin('base','v6OphWait'));

humanWait = ...
    getLastMetric( ...
        evalin('base','v6HumanWait'));

% ============================================================
% 37. READ UTILIZATION
% ============================================================

capture1Util = ...
    getLastMetric( ...
        evalin('base','v6Capture1Util'));

capture2Util = ...
    getLastMetric( ...
        evalin('base','v6Capture2Util'));

aiUtil = ...
    getLastMetric( ...
        evalin('base','v6AIUtil'));

ophUtil = ...
    getLastMetric( ...
        evalin('base','v6OphUtil'));

humanUtil = ...
    getLastMetric( ...
        evalin('base','v6HumanUtil'));

recapturePrepUtil = ...
    getLastMetric( ...
        evalin('base','v6RecapturePrepUtil'));

% ============================================================
% 38. DERIVED METRICS
% ============================================================

expectedPrimary = ...
    floor( ...
        simulationTime ...
        / arrivalPeriod) ...
    + 1;

primaryCompleted = ...
    sum(routeCounts) ...
    + recaptureComplete;

primaryIncomplete = ...
    max( ...
        0, ...
        expectedPrimary ...
        - primaryCompleted);

primaryCompletionFraction = ...
    primaryCompleted ...
    / max(1,expectedPrimary);

observedRecaptureFraction = ...
    recaptureComplete ...
    / max(1,primaryCompleted);

% ------------------------------------------------------------
% Workload accounting
%
% Each completed primary:
%   1 original capture
%
% Each completed recapture:
%   +1 additional capture
% ------------------------------------------------------------

captureWorkUnits = ...
    primaryCompleted ...
    + recaptureComplete;

effectiveCaptureDemandPerPrimary = ...
    captureWorkUnits ...
    / max(1,primaryCompleted);

extraCaptureLoadPercent = ...
    (effectiveCaptureDemandPerPrimary - 1) ...
    * 100;

observedPrimaryRate = ...
    primaryCompleted ...
    / simulationHours;

observedAnnualEquivalent = ...
    observedPrimaryRate ...
    * hoursPerDay ...
    * workingDays;

maxCaptureUtil = ...
    max( ...
        [capture1Util capture2Util]);

maxCaptureWait = ...
    max( ...
        [capture1Wait capture2Wait]);

captureStable = ...
    maxCaptureUtil < 0.95;

downstreamStable = ...
    aiUtil < 0.95 ...
    && ophUtil < 0.95 ...
    && humanUtil < 0.95;

systemStable = ...
    captureStable ...
    && downstreamStable;

% ============================================================
% 39. RESULT STRUCT
% ============================================================

result.scenario = ...
    'DISTRICT_100K_RECAPTURE_PATH_COMBINER_V1';

result.provenance.annualTarget = ...
    'REQUIREMENT';

result.provenance.captureTime = ...
    'ASSUMPTION';

result.provenance.aiTime = ...
    'MEASURED_SINGLE_REFERENCE_CASE';

result.provenance.routeMix = ...
    'ENGINEERING_TEST';

result.provenance.recapturePreparation = ...
    'ASSUMPTION';

result.provenance.postRecaptureClinicalOutcome = ...
    'NOT_INFERRED';

result.provenance.feedbackMerge = ...
    'SIMEVENTS_PATH_COMBINER';

result.provenance.outputMetrics = ...
    'SIMULATED';

result.primary.generated = ...
    expectedPrimary;

result.primary.completed = ...
    primaryCompleted;

result.primary.incompleteAtStop = ...
    primaryIncomplete;

result.primary.completionFraction = ...
    primaryCompletionFraction;

result.primary.observedRatePerHour = ...
    observedPrimaryRate;

result.primary.observedAnnualEquivalent = ...
    observedAnnualEquivalent;

result.routes.routine = ...
    routeCounts(1);

result.routes.ophthalmology = ...
    routeCounts(2);

result.routes.humanReview = ...
    routeCounts(3);

result.routes.reviewRecapture = ...
    routeCounts(4);

result.routes.recaptureComplete = ...
    recaptureComplete;

result.wait.capture1Sec = ...
    capture1Wait;

result.wait.capture2Sec = ...
    capture2Wait;

result.wait.aiSec = ...
    aiWait;

result.wait.ophthalmologySec = ...
    ophWait;

result.wait.humanReviewSec = ...
    humanWait;

result.utilization.capture1 = ...
    capture1Util;

result.utilization.capture2 = ...
    capture2Util;

result.utilization.ai = ...
    aiUtil;

result.utilization.ophthalmology = ...
    ophUtil;

result.utilization.humanReview = ...
    humanUtil;

result.utilization.recapturePreparation = ...
    recapturePrepUtil;

result.recapture.completed = ...
    recaptureComplete;

result.recapture.observedFraction = ...
    observedRecaptureFraction;

result.recapture.captureWorkUnits = ...
    captureWorkUnits;

result.recapture.effectiveCaptureDemandPerPrimary = ...
    effectiveCaptureDemandPerPrimary;

result.recapture.extraCaptureLoadPercent = ...
    extraCaptureLoadPercent;

result.captureStable = ...
    captureStable;

result.downstreamStable = ...
    downstreamStable;

result.systemStable = ...
    systemStable;

% ============================================================
% 40. PRINT RESULTS
% ============================================================

fprintf('\n');
fprintf('========================================================\n');
fprintf(' NETRAAI V6 RECAPTURE RESULTS\n');
fprintf('========================================================\n');

fprintf('\n--- PRIMARY TRACE OUTCOMES ---\n');

fprintf( ...
    'Routine                   : %.0f\n', ...
    routeCounts(1));

fprintf( ...
    'Ophthalmology             : %.0f\n', ...
    routeCounts(2));

fprintf( ...
    'Human Review              : %.0f\n', ...
    routeCounts(3));

fprintf( ...
    'Review / Recapture        : %.0f\n', ...
    routeCounts(4));

fprintf( ...
    'Completed recapture pass  : %.0f\n', ...
    recaptureComplete);

fprintf('\n--- PRIMARY COMPLETION ---\n');

fprintf( ...
    'Generated primary cases   : %.0f\n', ...
    expectedPrimary);

fprintf( ...
    'Completed primary cases   : %.0f\n', ...
    primaryCompleted);

fprintf( ...
    'Incomplete @ hard stop    : %.0f\n', ...
    primaryIncomplete);

fprintf( ...
    'Completion fraction       : %.4f\n', ...
    primaryCompletionFraction);

fprintf('\n--- QUEUE WAIT ---\n');

fprintf( ...
    'Capture Station 1         : %.3f s\n', ...
    capture1Wait);

fprintf( ...
    'Capture Station 2         : %.3f s\n', ...
    capture2Wait);

fprintf( ...
    'AI                        : %.3f s\n', ...
    aiWait);

fprintf( ...
    'Ophthalmology             : %.3f s\n', ...
    ophWait);

fprintf( ...
    'Human Review              : %.3f s\n', ...
    humanWait);

fprintf('\n--- RESOURCE UTILIZATION ---\n');

fprintf( ...
    'Capture Station 1         : %.4f\n', ...
    capture1Util);

fprintf( ...
    'Capture Station 2         : %.4f\n', ...
    capture2Util);

fprintf( ...
    'TRACE AI                  : %.4f\n', ...
    aiUtil);

fprintf( ...
    'Ophthalmologist           : %.4f\n', ...
    ophUtil);

fprintf( ...
    'Human Reviewer            : %.4f\n', ...
    humanUtil);

fprintf( ...
    'Recapture Preparation     : %.4f\n', ...
    recapturePrepUtil);

fprintf('\n--- RECAPTURE WORKLOAD ---\n');

fprintf( ...
    'Observed recapture passes : %.0f\n', ...
    recaptureComplete);

fprintf( ...
    'Observed recapture frac.  : %.4f\n', ...
    observedRecaptureFraction);

fprintf( ...
    'Effective captures/primary: %.4f\n', ...
    effectiveCaptureDemandPerPrimary);

fprintf( ...
    'Additional capture load   : %.2f%%\n', ...
    extraCaptureLoadPercent);

fprintf('\n--- THROUGHPUT ---\n');

fprintf( ...
    'Observed primary rate     : %.2f cases/hour\n', ...
    observedPrimaryRate);

fprintf( ...
    'Observed annual eq.       : %.0f/year\n', ...
    observedAnnualEquivalent);

fprintf('\n--- SYSTEM STATUS ---\n');

fprintf( ...
    'Maximum capture util      : %.4f\n', ...
    maxCaptureUtil);

fprintf( ...
    'Maximum capture wait      : %.3f s\n', ...
    maxCaptureWait);

fprintf( ...
    'Capture stable            : %d\n', ...
    captureStable);

fprintf( ...
    'Downstream stable         : %d\n', ...
    downstreamStable);

fprintf('\n');

if systemStable

    fprintf( ...
        'SYSTEM STATUS: STABLE UNDER CURRENT ENGINEERING TEST\n');

else

    fprintf( ...
        'SYSTEM STATUS: CAPACITY PRESSURE DETECTED\n');

end

fprintf('========================================================\n');

% ============================================================
% 41. V5 VS V6
% ============================================================

v5ResultFile = fullfile( ...
    resultsDir, ...
    'NetraAI_V5_ParallelCapture_Result.mat');

if exist(v5ResultFile,'file') == 2

    v5Data = load(v5ResultFile);

    if isfield(v5Data,'result')

        v5 = v5Data.result;

        fprintf('\n');
        fprintf('========================================================\n');
        fprintf(' V5 vs V6 RECAPTURE IMPACT\n');
        fprintf('========================================================\n');

        fprintf( ...
            'V5 Capture 1 util       : %.4f\n', ...
            v5.utilization.capture1);

        fprintf( ...
            'V6 Capture 1 util       : %.4f\n', ...
            capture1Util);

        fprintf( ...
            'V5 Capture 2 util       : %.4f\n', ...
            v5.utilization.capture2);

        fprintf( ...
            'V6 Capture 2 util       : %.4f\n', ...
            capture2Util);

        fprintf( ...
            'V5 AI util              : %.4f\n', ...
            v5.utilization.ai);

        fprintf( ...
            'V6 AI util              : %.4f\n', ...
            aiUtil);

        fprintf( ...
            'V5 max capture wait     : %.3f s\n', ...
            max( ...
                [v5.wait.capture1Sec ...
                 v5.wait.capture2Sec]));

        fprintf( ...
            'V6 max capture wait     : %.3f s\n', ...
            maxCaptureWait);

        fprintf( ...
            'Added capture workload  : %.2f%%\n', ...
            extraCaptureLoadPercent);

        fprintf('========================================================\n');

    end

end

% ============================================================
% 42. SAVE MAT RESULT
% ============================================================

resultMat = fullfile( ...
    resultsDir, ...
    'NetraAI_V6_Recapture_Result.mat');

save( ...
    resultMat, ...
    'result');

% ============================================================
% 43. SAVE TEXT REPORT
% ============================================================

reportFile = fullfile( ...
    resultsDir, ...
    'NetraAI_V6_Recapture_Report.txt');

fid = fopen( ...
    reportFile, ...
    'w');

if fid ~= -1

    fprintf(fid, ...
        'ANEYE / NetraAI Digital Twin V6\n');

    fprintf(fid, ...
        'Path-Combiner One-Pass Recapture Loop\n\n');

    fprintf(fid, ...
        'Feedback merge: SimEvents Path Combiner\n');

    fprintf(fid, ...
        'Post-recapture clinical outcome: NOT INFERRED\n');

    fprintf(fid, ...
        'Capture time: %.4f s [ASSUMPTION]\n', ...
        captureTime);

    fprintf(fid, ...
        'AI service: %.5f s [MEASURED_SINGLE_REFERENCE_CASE]\n', ...
        aiTime);

    fprintf(fid, ...
        'Recapture preparation: %.4f s [ASSUMPTION]\n\n', ...
        recapturePreparationTime);

    fprintf(fid, ...
        'PRIMARY\n');

    fprintf(fid, ...
        'Generated: %.0f\n', ...
        expectedPrimary);

    fprintf(fid, ...
        'Completed: %.0f\n', ...
        primaryCompleted);

    fprintf(fid, ...
        'Incomplete hard stop: %.0f\n', ...
        primaryIncomplete);

    fprintf(fid, ...
        'Completion fraction: %.6f\n\n', ...
        primaryCompletionFraction);

    fprintf(fid, ...
        'TRACE\n');

    fprintf(fid, ...
        'Routine: %.0f\n', ...
        routeCounts(1));

    fprintf(fid, ...
        'Ophthalmology: %.0f\n', ...
        routeCounts(2));

    fprintf(fid, ...
        'Human Review: %.0f\n', ...
        routeCounts(3));

    fprintf(fid, ...
        'Review/Recapture: %.0f\n', ...
        routeCounts(4));

    fprintf(fid, ...
        'Completed Recapture: %.0f\n\n', ...
        recaptureComplete);

    fprintf(fid, ...
        'RECAPTURE WORKLOAD\n');

    fprintf(fid, ...
        'Observed fraction: %.6f\n', ...
        observedRecaptureFraction);

    fprintf(fid, ...
        'Effective captures per primary: %.6f\n', ...
        effectiveCaptureDemandPerPrimary);

    fprintf(fid, ...
        'Additional capture load: %.4f%%\n\n', ...
        extraCaptureLoadPercent);

    fprintf(fid, ...
        'QUEUE WAIT\n');

    fprintf(fid, ...
        'Capture 1: %.6f s\n', ...
        capture1Wait);

    fprintf(fid, ...
        'Capture 2: %.6f s\n', ...
        capture2Wait);

    fprintf(fid, ...
        'AI: %.6f s\n', ...
        aiWait);

    fprintf(fid, ...
        'Ophthalmology: %.6f s\n', ...
        ophWait);

    fprintf(fid, ...
        'Human Review: %.6f s\n\n', ...
        humanWait);

    fprintf(fid, ...
        'UTILIZATION\n');

    fprintf(fid, ...
        'Capture 1: %.6f\n', ...
        capture1Util);

    fprintf(fid, ...
        'Capture 2: %.6f\n', ...
        capture2Util);

    fprintf(fid, ...
        'TRACE AI: %.6f\n', ...
        aiUtil);

    fprintf(fid, ...
        'Ophthalmology: %.6f\n', ...
        ophUtil);

    fprintf(fid, ...
        'Human Review: %.6f\n', ...
        humanUtil);

    fprintf(fid, ...
        'Recapture Preparation: %.6f\n\n', ...
        recapturePrepUtil);

    fprintf(fid, ...
        'SYSTEM\n');

    fprintf(fid, ...
        'Capture stable: %d\n', ...
        captureStable);

    fprintf(fid, ...
        'Downstream stable: %d\n', ...
        downstreamStable);

    fprintf(fid, ...
        'System stable: %d\n', ...
        systemStable);

    fclose(fid);

end

% ============================================================
% 44. FINAL SAVE
% ============================================================

save_system( ...
    mdl, ...
    modelFile);

fprintf('\nSaved V6 result:\n%s\n', ...
    resultMat);

fprintf('\nSaved V6 report:\n%s\n', ...
    reportFile);

fprintf('\nV6 model:\n%s\n', ...
    modelFile);

open_system(mdl);

end


% ============================================================
% HELPER: SET LOGGER VARIABLE
% ============================================================

function setLoggerVariable( ...
    mdl, ...
    blockName, ...
    variableName)

blockPath = ...
    [mdl '/' blockName];

try

    set_param( ...
        blockPath, ...
        'VariableName', ...
        variableName);

catch ME

    error( ...
        ['Unable to configure logger "' ...
         blockName ...
         '": ' ...
         ME.message]);

end

end


% ============================================================
% HELPER: FIND LEGACY SIMEVENTS BLOCK
% ============================================================

function blockPath = findLegacyBlock( ...
    rootLibrary, ...
    targetName)

blocks = find_system( ...
    rootLibrary, ...
    'LookUnderMasks', ...
    'all', ...
    'FollowLinks', ...
    'on', ...
    'Type', ...
    'Block');

blockPath = '';

for k = 1:length(blocks)

    cleanName = strrep( ...
        blocks{k}, ...
        sprintf('\n'), ...
        ' ');

    if ~isempty( ...
            strfind( ...
                cleanName, ...
                targetName))

        blockPath = blocks{k};

        break;

    end

end

if isempty(blockPath)

    error( ...
        ['Legacy SimEvents block not found: ' ...
         targetName]);

end

end


% ============================================================
% HELPER: FORCE NORMAL ENTITY CONNECTION
% ============================================================

function forceEntityConnection( ...
    model, ...
    source, ...
    destination)

srcHandles = get_param( ...
    source, ...
    'PortHandles');

dstHandles = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput( ...
    srcHandles, ...
    1);

dstPort = getEntityInput( ...
    dstHandles, ...
    1);

disconnectPortLine(srcPort);
disconnectPortLine(dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% HELPER: FORCE SPECIFIC OUTPUT CONNECTION
% ============================================================

function forceEntityOutputConnection( ...
    model, ...
    source, ...
    destination, ...
    outputIndex)

srcHandles = get_param( ...
    source, ...
    'PortHandles');

dstHandles = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput( ...
    srcHandles, ...
    outputIndex);

dstPort = getEntityInput( ...
    dstHandles, ...
    1);

disconnectPortLine(srcPort);
disconnectPortLine(dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% HELPER: FORCE SPECIFIC INPUT CONNECTION
% ============================================================

function forceEntityToInputConnection( ...
    model, ...
    source, ...
    destination, ...
    inputIndex)

srcHandles = get_param( ...
    source, ...
    'PortHandles');

dstHandles = get_param( ...
    destination, ...
    'PortHandles');

srcPort = getEntityOutput( ...
    srcHandles, ...
    1);

dstPort = getEntityInput( ...
    dstHandles, ...
    inputIndex);

disconnectPortLine(srcPort);
disconnectPortLine(dstPort);

add_line( ...
    model, ...
    srcPort, ...
    dstPort, ...
    'autorouting', ...
    'on');

end


% ============================================================
% HELPER: DISCONNECT PORT LINE
% ============================================================

function disconnectPortLine(portHandle)

if isempty(portHandle)
    return;
end

try

    lineHandle = get_param( ...
        portHandle, ...
        'Line');

    if ~isempty(lineHandle) && ...
            lineHandle ~= -1

        delete_line(lineHandle);

    end

catch
end

end


% ============================================================
% HELPER: ENTITY OUTPUT HANDLE
% ============================================================

function h = getEntityOutput( ...
    portHandles, ...
    index)

if isfield(portHandles,'RConn') && ...
        length(portHandles.RConn) >= index

    h = portHandles.RConn(index);

    return;

end

if isfield(portHandles,'Outport') && ...
        length(portHandles.Outport) >= index

    h = portHandles.Outport(index);

    return;

end

error( ...
    ['Unable to resolve entity output port ' ...
     num2str(index)]);

end


% ============================================================
% HELPER: ENTITY INPUT HANDLE
% ============================================================

function h = getEntityInput( ...
    portHandles, ...
    index)

if isfield(portHandles,'LConn') && ...
        length(portHandles.LConn) >= index

    h = portHandles.LConn(index);

    return;

end

if isfield(portHandles,'Inport') && ...
        length(portHandles.Inport) >= index

    h = portHandles.Inport(index);

    return;

end

error( ...
    ['Unable to resolve entity input port ' ...
     num2str(index)]);

end


% ============================================================
% HELPER: VERIFY FIRST ENTITY INPUT CONNECTED
% ============================================================

function verifyEntityInputConnected(blockPath)

portHandles = get_param( ...
    blockPath, ...
    'PortHandles');

inputPort = getEntityInput( ...
    portHandles, ...
    1);

lineHandle = get_param( ...
    inputPort, ...
    'Line');

if isempty(lineHandle) || ...
        lineHandle == -1

    error( ...
        ['Critical entity input disconnected: ' ...
         blockPath]);

end

fprintf( ...
    'CONNECTED: %s\n', ...
    blockPath);

end


% ============================================================
% HELPER: LAST WORKSPACE METRIC
% ============================================================

function value = getLastMetric(data)

if isempty(data)

    value = 0;

elseif size(data,2) >= 2

    value = data(end,2);

else

    value = data(end);

end

end